# -*- coding: utf-8 -*-
"""Ergänzungen für das Formelbuch: fehlende Formeln und die Kalkulationsschemas.

Die fehlenden Formeln sind aus den 17 Original-Prüfungen abgeleitet – überall
dort, wo eine Prüfungsaufgabe einen Rechenweg verlangt, den das Formelbuch
bisher nicht hergab (Akkordlohn, Naturwissenschaft/Technik, Elektrotechnik,
Statistik, einzelne Kosten- und Lagerkennzahlen).
"""
from rechenbar import v, rechne


def f(name, gleichung, hinweis=None, **kw):
    it = {'n': name, 'e': gleichung}
    if hinweis:
        it['d'] = hinweis
    it.update(kw)
    return it


def fr(name, gleichung, vars_, ausdruck, ergebnis, einheit='', dec=2, hinweis=None):
    """Formel mit Rechenweg."""
    it = f(name, gleichung, hinweis)
    it.update(rechne(vars_, ausdruck, ergebnis, einheit, dec))
    return it


# ------------------------------------------- Ergänzungen in bestehenden Gruppen
ERGAENZUNGEN = {
 "Prozent- & Zinsrechnung": [
   fr("Vermehrter Grundwert", "G = W · 100 ÷ (100 + p)",
      [v('W','Betrag inkl. Zuschlag','€'), v('p','Zuschlagssatz','%')],
      'W*100/(100+p)', 'Grundwert', '€',
      hinweis="Wenn der gegebene Wert den Zuschlag schon enthält (z. B. Brutto)."),
   fr("Verminderter Grundwert", "G = W · 100 ÷ (100 − p)",
      [v('W','Betrag nach Abzug','€'), v('p','Abzugssatz','%')],
      'W*100/(100-p)', 'Grundwert', '€',
      hinweis="Wenn vom gegebenen Wert bereits abgezogen wurde (z. B. nach Skonto)."),
 ],
 "Zuschlagskalkulation & Kostenstellen": [
   fr("Materialkosten", "MK = Materialeinzelkosten + Materialgemeinkosten",
      [v('MEK','Materialeinzelkosten','€'), v('mgk','MGK-Satz','%')],
      'MEK*(1+mgk/100)', 'Materialkosten', '€',
      hinweis="Die Materialgemeinkosten werden auf die Materialeinzelkosten aufgeschlagen."),
   fr("Fertigungskosten", "FK = Fertigungseinzelkosten + Fertigungsgemeinkosten + SEF",
      [v('FEK','Fertigungseinzelkosten','€'), v('fgk','FGK-Satz','%'),
       v('SEF','Sondereinzelkosten Fertigung','€',0)],
      'FEK*(1+fgk/100)+SEF', 'Fertigungskosten', '€',
      hinweis="Die Sondereinzelkosten der Fertigung tragen keine Gemeinkosten."),
   fr("Materialeinzelkosten (rückwärts)", "MEK = Materialkosten ÷ (1 + MGK-Satz ÷ 100)",
      [v('MK','Materialkosten','€'), v('mgk','MGK-Satz','%')],
      'MK/(1+mgk/100)', 'Materialeinzelkosten', '€',
      hinweis="Rückwärtskalkulation: aus den Materialkosten zurück auf die Einzelkosten."),
 ],
 "Kosten- & Leistungsrechnung": [
   fr("Variable Stückkosten (Differenzenmethode)", "kv = (K₂ − K₁) ÷ (x₂ − x₁)",
      [v('K2','Gesamtkosten bei Menge 2','€'), v('K1','Gesamtkosten bei Menge 1','€'),
       v('x2','Menge 2','Stück'), v('x1','Menge 1','Stück')],
      '(K2-K1)/(x2-x1)', 'variable Stückkosten', '€/Stück',
      hinweis="Zwei Kostenpunkte bei konstanten Fixkosten – der Kostenzuwachs ist rein variabel."),
   fr("Fixkosten aus Gesamtkosten", "Kf = K − kv · x",
      [v('K','Gesamtkosten','€'), v('kv','variable Stückkosten','€'), v('x','Menge','Stück')],
      'K-kv*x', 'Fixkosten', '€'),
   fr("Break-Even-Beschäftigungsgrad", "BG = Break-Even-Menge ÷ Kapazität · 100",
      [v('xbep','Break-Even-Menge','Stück'), v('kap','Kapazität','Stück')],
      'xbep/kap*100', 'Break-Even-Beschäftigungsgrad', '%',
      hinweis="Ab dieser Auslastung arbeitet der Betrieb in der Gewinnzone."),
   fr("Betriebsergebnis", "BE = Preis · Menge − Gesamtkosten",
      [v('p','Verkaufspreis','€'), v('x','Menge','Stück'), v('K','Gesamtkosten','€')],
      'p*x-K', 'Betriebsergebnis', '€',
      hinweis="Negativ = Verlust; die Menge liegt dann unter der Break-Even-Menge."),
 ],
 "Materialwirtschaft & Lager": [
   fr("Ø Lagerbestand (mit Sicherheitsbestand)", "Ø LB = Sicherheitsbestand + Bestellmenge ÷ 2",
      [v('SB','Sicherheitsbestand',''), v('BM','Bestellmenge','')],
      'SB+BM/2', 'Ø Lagerbestand', '', 2,
      hinweis="Bestellpunktverfahren bei gleichmäßigem Verbrauch."),
   fr("Tagesverbrauch", "Tagesverbrauch = Jahresbedarf ÷ Lagertage",
      [v('JB','Jahresbedarf',''), v('tage','Lagertage im Jahr','Tage',360)],
      'JB/tage', 'Tagesverbrauch', '', 4,
      hinweis="Kaufmännisch wird mit 360 Tagen gerechnet."),
   fr("Anzahl Bestellungen je Jahr", "n = Jahresbedarf ÷ Bestellmenge",
      [v('JB','Jahresbedarf',''), v('BM','Bestellmenge','')],
      'JB/BM', 'Bestellungen je Jahr', '', 2),
 ],
 "Statistik": [
   fr("Relativer Anteil (Prozentanteil)", "p = Teilmenge ÷ Grundmenge · 100",
      [v('g','Teilmenge (z. B. Fehler)',''), v('N','Grundmenge (z. B. Losgröße)','')],
      'g/N*100', 'relativer Anteil', '%'),
   fr("Erwartungswert in der Stichprobe", "x = Anteil in % · Stichprobenumfang ÷ 100",
      [v('p','Anteil','%'), v('n','Stichprobenumfang','Stück')],
      'p*n/100', 'erwartete Stückzahl', 'Stück',
      hinweis="Bei bekanntem Fehleranteil die zu erwartenden Fehlteile je Stichprobe."),
   fr("Gewichtetes Mittel", "x̄ = Σ(Wert · Gewicht) ÷ Σ Gewichte",
      [v('summe','Σ (Wert × Gewicht)',''), v('gew','Σ Gewichte','')],
      'summe/gew', 'gewichteter Mittelwert', '', 2),
 ],
 "Sozialversicherung – Beiträge (Stand 2025)": [
   fr("Beitrag zu einem Zweig", "Beitrag = Bruttoentgelt · Beitragssatz ÷ 100",
      [v('brutto','Bruttoentgelt','€'), v('satz','Beitragssatz','%')],
      'brutto*satz/100', 'Gesamtbeitrag', '€'),
   fr("Arbeitnehmeranteil (paritätisch)", "AN-Anteil = Bruttoentgelt · Beitragssatz ÷ 200",
      [v('brutto','Bruttoentgelt','€'), v('satz','Beitragssatz','%')],
      'brutto*satz/200', 'Arbeitnehmeranteil', '€',
      hinweis="Arbeitgeber und Arbeitnehmer tragen je die Hälfte."),
 ],
 "Transport- & Fuhrparkkosten": [
   fr("Selbstkosten je km (Vollkosten)", "k = (fixe + variable Jahreskosten) ÷ Jahresfahrleistung",
      [v('Kf','fixe Jahreskosten','€'), v('Kv','variable Jahreskosten','€'),
       v('km','Jahresfahrleistung','km')],
      '(Kf+Kv)/km', 'Selbstkosten je km', '€/km', 4),
   fr("Leerkilometeranteil", "Leerkm-Anteil = Leerkilometer ÷ Gesamtkilometer · 100",
      [v('leer','Leerkilometer','km'), v('ges','Gesamtkilometer','km')],
      'leer/ges*100', 'Leerkilometeranteil', '%',
      hinweis="Je niedriger, desto wirtschaftlicher der Fahrzeugeinsatz."),
 ],
}

# ------------------------------------------------------------- neue Gruppen
NEUE_GRUPPEN = [
 ("Personal & Zeit", {  # wird direkt hinter dieser Gruppe eingefügt
   "g": "Entgelt & Akkordlohn",
   "items": [
     fr("Akkordrichtsatz", "AR = Akkordgrundlohn · (1 + Akkordzuschlag ÷ 100)",
        [v('GL','Akkordgrundlohn','€/h'), v('z','Akkordzuschlag','%',10)],
        'GL*(1+z/100)', 'Akkordrichtsatz', '€/h',
        hinweis="Der Akkordzuschlag gleicht das Verdienstrisiko des Akkords aus."),
     fr("Normalleistung je Stunde", "Normalleistung = 60 min ÷ Vorgabezeit je Stück",
        [v('tv','Vorgabezeit je Stück','min')],
        '60/tv', 'Normalleistung', 'Stück/h'),
     fr("Stückgeld (Geldfaktor)", "Stückgeld = Akkordrichtsatz ÷ Normalleistung",
        [v('AR','Akkordrichtsatz','€/h'), v('NL','Normalleistung','Stück/h')],
        'AR/NL', 'Stückgeld', '€/Stück', 4,
        hinweis="Im Geldakkord wird je gefertigtem Stück ein fester Betrag gezahlt."),
     fr("Akkordlohn je Stunde (Geldakkord)", "Akkordlohn = Stückgeld · gefertigte Stückzahl",
        [v('SG','Stückgeld','€/Stück'), v('m','gefertigte Stück je Stunde','Stück/h')],
        'SG*m', 'Bruttostundenlohn', '€/h'),
     fr("Minutenfaktor (Zeitakkord)", "Minutenfaktor = Akkordrichtsatz ÷ 60",
        [v('AR','Akkordrichtsatz','€/h')],
        'AR/60', 'Minutenfaktor', '€/min', 4),
     fr("Akkordlohn (Zeitakkord)", "Lohn = Minutenfaktor · Vorgabezeit · Stückzahl",
        [v('MF','Minutenfaktor','€/min'), v('tv','Vorgabezeit je Stück','min'),
         v('m','Stückzahl','Stück')],
        'MF*tv*m', 'Akkordlohn', '€'),
     fr("Leistungsgrad", "LG = Ist-Leistung ÷ Normalleistung · 100",
        [v('ist','Ist-Leistung','Stück/h'), v('NL','Normalleistung','Stück/h')],
        'ist/NL*100', 'Leistungsgrad', '%'),
     fr("Lohnkosten je Stück", "Lohnkosten je Stück = Stundenlohn ÷ Stückzahl je Stunde",
        [v('lohn','Stundenlohn','€/h'), v('m','Stückzahl je Stunde','Stück/h')],
        'lohn/m', 'Lohnkosten je Stück', '€/Stück', 4,
        hinweis="Im Akkord bleiben sie konstant – der Stundenlohn steigt mit dem Leistungsgrad."),
     fr("Prämienlohn", "Lohn = Grundlohn + Prämie",
        [v('GL','Grundlohn','€'), v('pr','Prämie','€',0)],
        'GL+pr', 'Prämienlohn', '€',
        hinweis="Prämie z. B. für Menge, Qualität, Ersparnis oder Termintreue."),
     fr("Personalzusatzkosten", "Zusatzkosten = Bruttoentgelt · Zusatzkostensatz ÷ 100",
        [v('brutto','Bruttoentgelt','€'), v('satz','Zusatzkostensatz','%',80)],
        'brutto*satz/100', 'Personalzusatzkosten', '€',
        hinweis="Arbeitgeberanteile, Urlaub, Feiertage, Entgeltfortzahlung, Sonderzahlungen."),
     fr("Personalbedarf", "Personalbedarf = Arbeitsvolumen ÷ Jahresarbeitszeit je Mitarbeiter",
        [v('vol','Arbeitsvolumen','h'), v('jaz','Jahresarbeitszeit je MA','h',1600)],
        'vol/jaz', 'Personalbedarf', 'MA'),
   ]}),
 ("Ladungssicherung (Physik)", {
   "g": "Naturwissenschaft & Technik",
   "items": [
     fr("Dichte", "ρ = m ÷ V",
        [v('m','Masse','kg'), v('V','Volumen','dm³')], 'm/V', 'Dichte', 'kg/dm³', 4),
     fr("Masse aus Dichte und Volumen", "m = ρ · V",
        [v('rho','Dichte','kg/dm³'), v('V','Volumen','dm³')], 'rho*V', 'Masse', 'kg'),
     fr("Wärmemenge", "Q = m · c · Δϑ",
        [v('m','Masse','kg'), v('c','spez. Wärmekapazität','kJ/(kg·K)',4.19),
         v('dT','Temperaturdifferenz','K')],
        'm*c*dT', 'Wärmemenge', 'kJ',
        hinweis="c für Wasser ≈ 4,19 kJ/(kg·K)."),
     fr("Mischungstemperatur", "ϑM = (m₁ · ϑ₁ + m₂ · ϑ₂) ÷ (m₁ + m₂)",
        [v('m1','Masse 1','kg'), v('T1','Temperatur 1','°C'),
         v('m2','Masse 2','kg'), v('T2','Temperatur 2','°C')],
        '(m1*T1+m2*T2)/(m1+m2)', 'Mischungstemperatur', '°C',
        hinweis="Gleiche Stoffe; die spezifische Wärmekapazität kürzt sich heraus."),
     fr("Zumischmenge für eine Zieltemperatur", "m₂ = m₁ · (ϑ₁ − ϑM) ÷ (ϑM − ϑ₂)",
        [v('m1','vorhandene Menge','kg'), v('T1','Ausgangstemperatur','°C'),
         v('TM','Zieltemperatur','°C'), v('T2','Temperatur der Zumischung','°C')],
        'm1*(T1-TM)/(TM-T2)', 'benötigte Zumischmenge', 'kg',
        hinweis="Bei Wasser (ρ = 1,0 kg/l) entspricht 1 kg genau 1 Liter."),
     fr("Längenausdehnung", "Δl = l₀ · α · ΔT",
        [v('l0','Ausgangslänge','m'), v('alpha','Längenausdehnungskoeffizient','1/K',0.000012),
         v('dT','Temperaturdifferenz','K')],
        'l0*alpha*dT', 'Längenänderung', 'm', 6,
        hinweis="Stahl α ≈ 12 · 10⁻⁶ 1/K."),
     fr("Volumenausdehnung", "V = V₀ · (1 + γ · ΔT)",
        [v('V0','Ausgangsvolumen','l'), v('gamma','Volumenausdehnungskoeffizient','1/K',0.0011),
         v('dT','Temperaturdifferenz','K')],
        'V0*(1+gamma*dT)', 'Volumen nach Erwärmung', 'l', 3,
        hinweis="Benzin γ ≈ 0,0011 1/K, Diesel ≈ 0,0008 1/K."),
     fr("Einfüllmenge bei späterer Erwärmung", "V = V_zul · (1 − γ · ΔT)",
        [v('Vzul','zulässiges Volumen im Betrieb','l'),
         v('gamma','Volumenausdehnungskoeffizient','1/K',0.0011),
         v('dT','Temperaturdifferenz','K')],
        'Vzul*(1-gamma*dT)', 'einzufüllendes Volumen', 'l', 3,
        hinweis="So bleibt der Tank nach dem Erwärmen genau beim zulässigen Füllgrad."),
     fr("Energie aus dem Heizwert", "Q = Hi · m",
        [v('Hi','Heizwert','kJ/kg',42000), v('m','Kraftstoffmasse','kg')],
        'Hi*m', 'zugeführte Energie', 'kJ',
        hinweis="Benzin ≈ 42.000 kJ/kg, Diesel ≈ 42.500 kJ/kg."),
     fr("Wirkungsgrad", "η = abgegebene Leistung ÷ zugeführte Leistung · 100",
        [v('Pab','abgegebene Leistung','kW'), v('Pzu','zugeführte Leistung','kW')],
        'Pab/Pzu*100', 'Wirkungsgrad', '%'),
     fr("Gesamtwirkungsgrad", "η_ges = η₁ · η₂ ÷ 100",
        [v('e1','Wirkungsgrad 1','%'), v('e2','Wirkungsgrad 2','%')],
        'e1*e2/100', 'Gesamtwirkungsgrad', '%',
        hinweis="Bei hintereinandergeschalteten Stufen multiplizieren sich die Wirkungsgrade."),
     fr("Hangabtriebsbeschleunigung", "a = g · sin α",
        [v('g','Fallbeschleunigung','m/s²',9.81), v('alpha','Steigungswinkel','°')],
        'g*sin(alpha)', 'Hangabtriebsbeschleunigung', 'm/s²', 3,
        hinweis="Massenunabhängig – die Masse kürzt sich heraus."),
     fr("Normalbeschleunigung an der Steigung", "a_N = g · cos α",
        [v('g','Fallbeschleunigung','m/s²',9.81), v('alpha','Steigungswinkel','°')],
        'g*cos(alpha)', 'Normalbeschleunigung', 'm/s²', 3),
     fr("Hangabtriebskraft", "F_H = F_G · sin α",
        [v('FG','Gewichtskraft','N'), v('alpha','Steigungswinkel','°')],
        'FG*sin(alpha)', 'Hangabtriebskraft', 'N'),
     fr("Kippgrenze (Abheben der Vorderachse)", "a_max = a_N · Achsabstand ÷ Schwerpunkthöhe",
        [v('aN','Normalbeschleunigung','m/s²'), v('l','Abstand Schwerpunkt–Hinterachse','m'),
         v('h','Schwerpunkthöhe','m')],
        'aN*l/h', 'Grenzbeschleunigung', 'm/s²', 3,
        hinweis="Momentengleichgewicht um die Hinterachse."),
     fr("Steigung in Prozent", "Steigung = Höhenunterschied ÷ waagerechte Strecke · 100",
        [v('h','Höhenunterschied','m'), v('s','waagerechte Strecke','m')],
        'h/s*100', 'Steigung', '%'),
     fr("Kraft", "F = m · a",
        [v('m','Masse','kg'), v('a','Beschleunigung','m/s²')], 'm*a', 'Kraft', 'N'),
     fr("Beschleunigung", "a = Δv ÷ Δt",
        [v('dv','Geschwindigkeitsänderung','m/s'), v('dt','Zeit','s')],
        'dv/dt', 'Beschleunigung', 'm/s²', 3),
     fr("Bremsweg (gleichmäßige Verzögerung)", "s = v² ÷ (2 · a)",
        [v('vv','Geschwindigkeit','m/s'), v('a','Verzögerung','m/s²')],
        'vv^2/(2*a)', 'Bremsweg', 'm',
        hinweis="v in m/s: km/h ÷ 3,6."),
     fr("Arbeit", "W = F · s",
        [v('F','Kraft','N'), v('s','Weg','m')], 'F*s', 'Arbeit', 'J'),
     fr("Mechanische Leistung", "P = W ÷ t",
        [v('W','Arbeit','J'), v('t','Zeit','s')], 'W/t', 'Leistung', 'W'),
     fr("Winkelgeschwindigkeit aus der Drehzahl", "ω = 2 · π · n ÷ 60",
        [v('n','Drehzahl','1/min')], '2*pi*n/60', 'Winkelgeschwindigkeit', '1/s'),
     fr("Drehmoment aus Leistung und Drehzahl", "M = P ÷ ω",
        [v('P','abgegebene Leistung','W'), v('w','Winkelgeschwindigkeit','1/s')],
        'P/w', 'Drehmoment', 'Nm'),
     fr("Drehmoment aus Kraft und Hebelarm", "M = F · r",
        [v('F','Kraft','N'), v('r','Hebelarm','m')], 'F*r', 'Drehmoment', 'Nm'),
     fr("Kreisfläche", "A = π · d² ÷ 4",
        [v('d','Durchmesser','m')], 'pi*d^2/4', 'Fläche', 'm²', 4),
     fr("Zylindervolumen", "V = π · d² ÷ 4 · h",
        [v('d','Durchmesser','m'), v('h','Höhe','m')], 'pi*d^2/4*h', 'Volumen', 'm³', 4),
   ]}),
 ("Naturwissenschaft & Technik", {
   "g": "Elektrotechnik",
   "items": [
     fr("Ohmsches Gesetz – Spannung", "U = R · I",
        [v('R','Widerstand','Ω'), v('I','Stromstärke','A')], 'R*I', 'Spannung', 'V'),
     fr("Ohmsches Gesetz – Stromstärke", "I = U ÷ R",
        [v('U','Spannung','V'), v('R','Widerstand','Ω')], 'U/R', 'Stromstärke', 'A', 3),
     fr("Ohmsches Gesetz – Widerstand", "R = U ÷ I",
        [v('U','Spannung','V'), v('I','Stromstärke','A')], 'U/I', 'Widerstand', 'Ω'),
     fr("Reihenschaltung von Widerständen", "R_ges = R₁ + R₂",
        [v('R1','Widerstand 1','Ω'), v('R2','Widerstand 2','Ω')],
        'R1+R2', 'Gesamtwiderstand', 'Ω',
        hinweis="Durch alle Widerstände fließt derselbe Strom."),
     fr("Parallelschaltung von Widerständen", "R_ges = (R₁ · R₂) ÷ (R₁ + R₂)",
        [v('R1','Widerstand 1','Ω'), v('R2','Widerstand 2','Ω')],
        'R1*R2/(R1+R2)', 'Gesamtwiderstand', 'Ω',
        hinweis="An allen Widerständen liegt dieselbe Spannung."),
     fr("Leistung (Gleichstrom)", "P = U · I",
        [v('U','Spannung','V'), v('I','Stromstärke','A')], 'U*I', 'Leistung', 'W'),
     fr("Leistung (Wechselstrom)", "P = U · I · cos φ",
        [v('U','Spannung','V'), v('I','Stromstärke','A'), v('cosphi','Leistungsfaktor cos φ','',0.85)],
        'U*I*cosphi', 'Wirkleistung', 'W',
        hinweis="Der Leistungsfaktor steht auf dem Typenschild des Motors."),
     fr("Leistung (Drehstrom)", "P = √3 · U · I · cos φ",
        [v('U','Spannung','V',400), v('I','Stromstärke','A'),
         v('cosphi','Leistungsfaktor cos φ','',0.85)],
        'sqrt(3)*U*I*cosphi', 'Wirkleistung', 'W'),
     fr("Leistung am Widerstand", "P = I² · R",
        [v('I','Stromstärke','A'), v('R','Widerstand','Ω')], 'I^2*R', 'Leistung', 'W'),
     fr("Elektrische Arbeit", "W = P · t",
        [v('P','Leistung','kW'), v('t','Zeit','h')], 'P*t', 'elektrische Arbeit', 'kWh'),
     fr("Stromkosten", "Kosten = elektrische Arbeit · Arbeitspreis",
        [v('W','elektrische Arbeit','kWh'), v('preis','Arbeitspreis','€/kWh',0.30)],
        'W*preis', 'Stromkosten', '€'),
     fr("Scheinleistung", "S = U · I",
        [v('U','Spannung','V'), v('I','Stromstärke','A')], 'U*I', 'Scheinleistung', 'VA',
        hinweis="Notstromaggregate werden in kVA angegeben – bei cos φ = 1 entspricht 1 kVA = 1 kW."),
   ]}),
]

# ---------------------------------------------------------- Kalkulationsschemas
# Zeilentypen: in = Eingabe, pct = Prozentaufschlag auf eine Bezugszeile,
# ih  = "im Hundert" (Prozentsatz bezieht sich auf die Summenzeile darunter),
# sum = Summenzeile (of: Bestandteile, "-X" zieht ab; ih: Im-Hundert-Zeilen).
SCHEMAS = [
 {"id": "zuschlag",
  "n": "Zuschlagskalkulation (Industrie)",
  "d": "Von den Materialeinzelkosten bis zum Listenverkaufspreis. Lass genau eine "
       "Kostenzeile frei und trage dafür einen Betrag weiter unten ein – dann rechnet "
       "das Schema rückwärts (z. B. Materialeinzelkosten aus dem Listenverkaufspreis).",
  "rows": [
    {"t":"in", "k":"MEK","n":"Materialeinzelkosten"},
    {"t":"pct","k":"MGK","n":"+ Materialgemeinkosten","base":"MEK","rn":"MGK-Satz","rd":25},
    {"t":"sum","k":"MK", "n":"= Materialkosten","of":["MEK","MGK"]},
    {"t":"in", "k":"FEK","n":"Fertigungseinzelkosten (Fertigungslöhne)"},
    {"t":"pct","k":"FGK","n":"+ Fertigungsgemeinkosten","base":"FEK","rn":"FGK-Satz","rd":210},
    {"t":"in", "k":"SEF","n":"+ Sondereinzelkosten der Fertigung","opt":True},
    {"t":"sum","k":"FK", "n":"= Fertigungskosten","of":["FEK","FGK","SEF"]},
    {"t":"sum","k":"HK", "n":"= Herstellkosten","of":["MK","FK"]},
    {"t":"pct","k":"VwGK","n":"+ Verwaltungsgemeinkosten","base":"HK","rn":"VwGK-Satz","rd":15},
    {"t":"pct","k":"VtGK","n":"+ Vertriebsgemeinkosten","base":"HK","rn":"VtGK-Satz","rd":5},
    {"t":"in", "k":"SEV","n":"+ Sondereinzelkosten des Vertriebs","opt":True},
    {"t":"sum","k":"SK", "n":"= Selbstkosten","of":["HK","VwGK","VtGK","SEV"]},
    {"t":"pct","k":"GEW","n":"+ Gewinnzuschlag","base":"SK","rn":"Gewinnsatz","rd":10},
    {"t":"sum","k":"BVP","n":"= Barverkaufspreis","of":["SK","GEW"]},
    {"t":"ih", "k":"SKO","n":"+ Kundenskonto","rn":"Skontosatz","rd":0},
    {"t":"ih", "k":"PRO","n":"+ Vertreterprovision","rn":"Provisionssatz","rd":0},
    {"t":"sum","k":"ZVP","n":"= Zielverkaufspreis","of":["BVP"],"ih":["SKO","PRO"]},
    {"t":"ih", "k":"RAB","n":"+ Kundenrabatt","rn":"Rabattsatz","rd":0},
    {"t":"sum","k":"LVP","n":"= Listenverkaufspreis (netto)","of":["ZVP"],"ih":["RAB"]}
  ]},
 {"id": "einkauf",
  "n": "Handelskalkulation – Bezugspreis",
  "d": "Vom Listeneinkaufspreis des Lieferanten zum Einstandspreis. Rabatt und Skonto "
       "werden nacheinander abgezogen, die Bezugskosten danach addiert.",
  "rows": [
    {"t":"in", "k":"LEP","n":"Listeneinkaufspreis"},
    {"t":"pct","k":"LRA","n":"− Liefererrabatt","base":"LEP","rn":"Rabattsatz","rd":0},
    {"t":"sum","k":"ZEP","n":"= Zieleinkaufspreis","of":["LEP","-LRA"]},
    {"t":"pct","k":"LSK","n":"− Liefererskonto","base":"ZEP","rn":"Skontosatz","rd":0},
    {"t":"sum","k":"BEP","n":"= Bareinkaufspreis","of":["ZEP","-LSK"]},
    {"t":"in", "k":"BZK","n":"+ Bezugskosten","opt":True},
    {"t":"sum","k":"BP", "n":"= Bezugspreis (Einstandspreis)","of":["BEP","BZK"]}
  ]},
 {"id": "verkauf",
  "n": "Handelskalkulation – Verkaufspreis",
  "d": "Vom Bezugspreis zum Listenverkaufspreis. Skonto, Provision und Rabatt rechnen "
       "„im Hundert“ – sie beziehen sich auf den jeweils höheren Preis.",
  "rows": [
    {"t":"in", "k":"BP", "n":"Bezugspreis (Einstandspreis)"},
    {"t":"pct","k":"HKO","n":"+ Handlungskosten","base":"BP","rn":"Handlungskostenzuschlag","rd":0},
    {"t":"sum","k":"SK", "n":"= Selbstkosten","of":["BP","HKO"]},
    {"t":"pct","k":"GEW","n":"+ Gewinnzuschlag","base":"SK","rn":"Gewinnsatz","rd":0},
    {"t":"sum","k":"BVP","n":"= Barverkaufspreis","of":["SK","GEW"]},
    {"t":"ih", "k":"SKO","n":"+ Kundenskonto","rn":"Skontosatz","rd":0},
    {"t":"ih", "k":"PRO","n":"+ Vertreterprovision","rn":"Provisionssatz","rd":0},
    {"t":"sum","k":"ZVP","n":"= Zielverkaufspreis","of":["BVP"],"ih":["SKO","PRO"]},
    {"t":"ih", "k":"RAB","n":"+ Kundenrabatt","rn":"Rabattsatz","rd":0},
    {"t":"sum","k":"LVP","n":"= Listenverkaufspreis (netto)","of":["ZVP"],"ih":["RAB"]}
  ]}
]
