# -*- coding: utf-8 -*-
"""Musterlösungen zu den IHK-Prüfungen.

Schlüssel: "<Handlungsbereich-Kürzel>|<Datum>|<Aufgabe>|<Teilaufgabe>"
Werte: a = Musterlösung, e = Merksatz/Hinweis (optional)

Die Lösungen sind fachlich erarbeitet und an der jeweiligen Punktzahl
ausgerichtet (Faustregel: 2 Punkte je verlangtem Element). Sie stammen NICHT
von der IHK – die Original-PDFs enthalten keine Lösungen.
"""

LOESUNGEN = {

# ══════════════ Organisation und Kommunikation · 12. November 2025 ══════════

"OK|12. November 2025|1|a": {
 "a": "Unterweisungen verfolgen im Betrieb drei zentrale Zielsetzungen:\n\n"
      "1. Sicherheit und Gesundheitsschutz: Die Beschäftigten sollen Gefährdungen "
      "an ihrem Arbeitsplatz erkennen und sich sicher verhalten. Unfälle, "
      "Berufskrankheiten und Sachschäden werden dadurch vermieden – etwa beim "
      "Rangieren, beim Arbeiten in der Werkstatt oder beim Sichern der Ladung.\n\n"
      "2. Erfüllung der gesetzlichen Pflicht und Rechtssicherheit: Der Arbeitgeber "
      "ist nach § 12 ArbSchG und § 4 DGUV Vorschrift 1 verpflichtet, vor Aufnahme "
      "der Tätigkeit und danach mindestens jährlich zu unterweisen. Die "
      "dokumentierte Unterweisung ist der Nachweis, dass diese Pflicht erfüllt "
      "wurde; sie schützt das Unternehmen und mich als Führungskraft vor Bußgeldern "
      "und Haftungsansprüchen.\n\n"
      "3. Qualität und Wirtschaftlichkeit: Einheitlich unterwiesene Mitarbeiter "
      "arbeiten nach denselben Standards. Das senkt Fehler, Beanstandungen bei "
      "Kontrollen und Folgekosten – im vorliegenden Fall unmittelbar bei "
      "Lastverteilung und Sozialvorschriften – und stützt zugleich die Forderungen "
      "des Qualitätsmanagements nach DIN EN ISO 9001.",
 "e": "Merke: Unterweisung ist Pflicht (§ 12 ArbSchG), mindestens jährlich, vor "
      "Aufnahme der Tätigkeit, bei Änderungen und nach Unfällen – immer schriftlich "
      "dokumentiert mit Unterschrift."
},
"OK|12. November 2025|1|b": {
 "a": "Vier Maßnahmen zur systematischen Ermittlung des Unterweisungsbedarfs:\n\n"
      "1. Auswertung der Gefährdungsbeurteilung (§ 5 ArbSchG): Aus jeder ermittelten "
      "Gefährdung leitet sich unmittelbar ein Unterweisungsinhalt ab. "
      "Beispiel: Die Beurteilung der Werkstatt zeigt Gefährdungen beim Arbeiten "
      "unter angehobenen Fahrzeugen – daraus folgt eine Unterweisung zur sicheren "
      "Bedienung der Hebebühne.\n\n"
      "2. Auswertung von Unfall-, Schadens- und Beinaheunfallstatistiken: "
      "Häufungen zeigen, wo Verhalten korrigiert werden muss. "
      "Beispiel: Mehrere Rangierschäden am Betriebshof führen zu einer Unterweisung "
      "über Rangieren und Einweisen.\n\n"
      "3. Auswertung externer Kontroll- und Prüfergebnisse: Beanstandungen von "
      "Behörden, Berufsgenossenschaft oder aus internen Audits benennen den Bedarf "
      "konkret. Beispiel: Die BALM-Kontrolle beanstandete die Lastverteilung – "
      "daraus folgt eine Unterweisung zu Achslasten und Ladungssicherung.\n\n"
      "4. Soll-Ist-Vergleich über Qualifikationsmatrix und Mitarbeitergespräche: "
      "Anforderungsprofil und tatsächlicher Kenntnisstand werden gegenübergestellt. "
      "Beispiel: Das Gespräch zeigt, dass zwei Fahrer die Bedienung des neuen "
      "digitalen Kontrollgeräts der zweiten Generation nicht sicher beherrschen.\n\n"
      "Ergänzend liefern Änderungen von Rechtsvorschriften, neue Fahrzeuge oder "
      "Arbeitsverfahren sowie Begehungen von Fachkraft für Arbeitssicherheit und "
      "Betriebsarzt (ASA-Sitzungen) laufend weiteren Bedarf.",
 "e": "Bedarf entsteht immer aus vier Quellen: Gefährdungen, Vorfälle, "
      "Beanstandungen und Qualifikationslücken."
},
"OK|12. November 2025|1|c": {
 "a": "Für das Fahrpersonal dieses Unternehmens sind vor allem drei Themenbereiche "
      "zu empfehlen – sie ergeben sich unmittelbar aus den Kontrollbeanstandungen "
      "und dem Fuhrpark:\n\n"
      "1. Sozialvorschriften im Straßenverkehr: Lenk- und Ruhezeiten nach "
      "VO (EG) 561/2006, Arbeitszeit nach ArbZG, korrekte Bedienung des digitalen "
      "Kontrollgeräts, Nachweispflichten und Mitführpflichten sowie das Verhalten "
      "bei Kontrollen. Anlass ist die Beanstandung im Bereich der Sozialvorschriften.\n\n"
      "2. Ladungssicherung und Lastverteilung: Physikalische Grundlagen der "
      "Massenkräfte, Sicherungsarten, zulässige Achslasten und zulässiges "
      "Gesamtgewicht, Lastverteilungsplan, Verantwortlichkeiten von Fahrer, Verlader "
      "und Halter nach § 22 StVO und § 31 StVZO. Anlass sind die festgestellten "
      "Mängel bei der Lastverteilung.\n\n"
      "3. Arbeitssicherheit und Verhalten im Fahrbetrieb: Sicheres Ein- und "
      "Aussteigen, Absichern des Fahrzeugs, persönliche Schutzausrüstung, "
      "Verhalten bei Unfall und Panne sowie – wegen der Omnibusse – Umgang mit "
      "Fahrgästen, Barrierefreiheit und Evakuierung.\n\n"
      "Sinnvoll ergänzen lässt sich dies durch wirtschaftliche und "
      "vorausschauende Fahrweise, die zugleich Kraftstoff- und Verschleißkosten senkt.",
 "e": "Themen immer aus dem konkreten Anlass ableiten: Kontrollbeanstandung → "
      "passender Unterweisungsinhalt."
},

"OK|12. November 2025|2|a": {
 "a": "Jährliche Fahrzeugkosten des Sattelkraftfahrzeugs\n\n"
      "Vorbemerkung: Der Reifensatz (6.000 €) wird aus den Anschaffungskosten "
      "herausgerechnet, da Reifen als verbrauchsabhängige Kosten laufleistungsbezogen "
      "erfasst werden. Abschreibungsbasis sind somit 174.000 €.\n\n"
      "FESTE KOSTEN (zeitabhängig)\n"
      "Kalkulatorische Abschreibung: (174.000 € − 20.000 €) ÷ 8 Jahre = 19.250,00 €\n"
      "Kalkulatorische Zinsen: (174.000 € + 20.000 €) ÷ 2 = 97.000 € × 5 % = 4.850,00 €\n"
      "Steuern und Versicherungen: 6.700,00 €\n"
      "Personalkosten: 3.500 € × 12 = 42.000 €; × 1,35 (35 % Lohnnebenkosten) "
      "= 56.700 €; × 1,2 (Personaleinsatzfaktor) = 68.040,00 €\n"
      "Gemeinkostenumlage: 10.000,00 €\n"
      "Summe feste Kosten: 108.840,00 €\n\n"
      "VARIABLE KOSTEN (bei 100.000 km)\n"
      "Kraftstoff: 30 l/100 km → 30.000 l × 1,30 €/l = 39.000,00 €\n"
      "Schmierstoffe: 100.000 km ÷ 1.000 × 2,80 € = 280,00 €\n"
      "Reifen: 6.000 € ÷ 120.000 km = 0,05 €/km × 100.000 km = 5.000,00 €\n"
      "Reparaturen und Wartung: 15.000,00 €\n"
      "Summe variable Kosten: 59.280,00 €\n\n"
      "GESAMTKOSTEN PRO JAHR: 108.840,00 € + 59.280,00 € = 168.120,00 €\n"
      "Zum Vergleich: 1,68 € je Kilometer bzw. 730,96 € je Einsatztag.",
 "e": "Aufbau merken: feste Kosten (Abschreibung, Zinsen, Steuern/Versicherung, "
      "Personal, Gemeinkosten) + variable Kosten (Kraftstoff, Schmierstoffe, Reifen, "
      "Reparatur) = Gesamtkosten."
},
"OK|12. November 2025|2|b": {
 "a": "Erlöse pro Jahr: 690 €/Einsatztag × 230 Einsatztage = 158.700,00 €\n"
      "Kosten pro Jahr: 168.120,00 €\n\n"
      "Wirtschaftlichkeit = Erlöse ÷ Kosten = 158.700 € ÷ 168.120 € = 0,944 "
      "bzw. 94,4 %\n\n"
      "Bewertung: Die Wirtschaftlichkeit liegt unter 1 (bzw. unter 100 %). Das "
      "Fahrzeug erwirtschaftet seine Kosten nicht und fährt einen Verlust von "
      "168.120 € − 158.700 € = 9.420,00 € pro Jahr ein. Um kostendeckend zu "
      "arbeiten, müsste der Tageserlös auf mindestens 168.120 € ÷ 230 = 730,96 € "
      "steigen. Das bestätigt das unterdurchschnittliche Betriebsergebnis der "
      "Sparte; Handlungsbedarf besteht sowohl auf der Erlös- als auch auf der "
      "Kostenseite.",
 "e": "Wirtschaftlichkeit = Leistung ÷ Kosten. Wert über 1 = wirtschaftlich, "
      "unter 1 = unwirtschaftlich."
},
"OK|12. November 2025|2|c": {
 "a": "Vier Vorschläge zur Verbesserung der Wirtschaftlichkeit:\n\n"
      "1. Erlöse erhöhen: Frachtraten nachverhandeln beziehungsweise an die "
      "gestiegenen Kosten anpassen und die Einsatztage besser auslasten "
      "(Rückladungen akquirieren, Leerkilometer senken).\n\n"
      "2. Kraftstoffkosten senken: Schulung in vorausschauender Fahrweise, "
      "Telematik- und Verbrauchsauswertung je Fahrer, Reifendruckkontrolle sowie "
      "Einkauf über Rahmenverträge und Eigenverbrauchstankstelle.\n\n"
      "3. Instandhaltungskosten senken: Vorbeugende Wartung in der eigenen "
      "Werkstatt statt teurer Ausfallreparaturen, Auswertung der Schadenshäufigkeit "
      "je Fahrzeug und konsequente Aussonderung von Kostentreibern.\n\n"
      "4. Kapitalbindung und Fixkosten optimieren: Nutzungsdauer und "
      "Beschaffungsform prüfen (Kauf, Leasing, Miete), günstigere Finanzierung, "
      "Versicherungen mit angepasster Selbstbeteiligung neu ausschreiben sowie "
      "den Personaleinsatzfaktor durch bessere Dienst- und Urlaubsplanung senken.",
 "e": "Immer beide Hebel nennen: Erlöse steigern UND Kosten senken."
},

"OK|12. November 2025|3|a": {
 "a": "Vier Fragestellungen für die Zusammensetzung der Projektgruppe:\n\n"
      "1. Welche Fachkompetenzen werden für das Auditziel benötigt, und sind alle "
      "betroffenen Bereiche vertreten? – Werkstatt, Disposition, Fahrpersonal, "
      "Verwaltung und der Qualitätsmanagementbeauftragte müssen ihre Prozesse "
      "selbst einbringen können.\n\n"
      "2. Wie groß soll die Gruppe sein, damit sie arbeitsfähig bleibt? – "
      "Erfahrungsgemäß sind fünf bis acht Mitglieder sinnvoll; größere Gruppen "
      "verlieren an Verbindlichkeit und Tempo.\n\n"
      "3. Welche Befugnisse und Rollen hat die Gruppe, und wer übernimmt sie? – "
      "Zu klären sind Projektleitung, Moderation, Protokoll, Entscheidungs- und "
      "Budgetkompetenz sowie die Berichtswege zur Geschäftsführung.\n\n"
      "4. Stehen die vorgesehenen Mitglieder zeitlich tatsächlich zur Verfügung? – "
      "Erforderlich sind eine verbindliche Freistellung vom Tagesgeschäft und die "
      "Abstimmung mit der Dienstplanung, damit die Mitarbeit nicht am "
      "Betriebsalltag scheitert.\n\n"
      "Ergänzend ist zu fragen, ob die Persönlichkeiten und Teamrollen zueinander "
      "passen und ob der Betriebsrat nach § 87 BetrVG zu beteiligen ist.",
 "e": "Vier Leitfragen: Welche Kompetenzen? Wie groß? Welche Rollen und Befugnisse? "
      "Welche Verfügbarkeit?"
},
"OK|12. November 2025|3|b": {
 "a": "Bei einer geteilten Moderation führen zwei Personen die Sitzung gemeinsam. "
      "Ein mögliches Vorgehen lässt sich an zwei Aspekten beschreiben:\n\n"
      "1. Aufteilung nach Rollen: Einer moderiert den Prozess – er führt durch die "
      "Tagesordnung, erteilt das Wort, achtet auf Zeit und Gesprächsregeln. Der "
      "andere übernimmt die Visualisierung und Dokumentation – er hält Ergebnisse "
      "an Flipchart oder Whiteboard fest, protokolliert Beschlüsse und behält "
      "offene Punkte im Blick. Vorteil: Der moderierende Part kann sich ganz auf "
      "die Gruppe konzentrieren, während nichts verloren geht.\n\n"
      "2. Aufteilung nach Themenblöcken: Jeder moderiert den Abschnitt, für den er "
      "fachlich zuständig ist – der QM-Beauftragte die Normanforderungen der "
      "DIN EN ISO 9001 und den Ablauf des Audits, ich als Fuhrparkleiter die "
      "operativen Themen aus Werkstatt und Fahrbetrieb. Vorteil: höhere fachliche "
      "Glaubwürdigkeit und Akzeptanz; der jeweils nicht moderierende Partner kann "
      "die Gruppe beobachten und bei Stockungen eingreifen.\n\n"
      "Voraussetzung ist in beiden Fällen eine klare Absprache vor der Sitzung "
      "über Rollen, Übergabepunkte und Zeitrahmen, damit die Doppelbesetzung nicht "
      "zu Verwirrung führt.",
 "e": "Geteilte Moderation entlastet und schafft eine Beobachterrolle – setzt aber "
      "klare Absprachen voraus."
},

"OK|12. November 2025|4|a": {
 "a": "Mögliche Fragestellung: „Was sollen die Zuhörer nach meiner Präsentation "
      "wissen, können oder entschieden haben?“\n\n"
      "Diese Frage zwingt dazu, das Ziel vom Ergebnis her zu denken, und lässt sich "
      "in die drei üblichen Zielarten aufschlüsseln: informieren (Wissen "
      "vermitteln), überzeugen beziehungsweise motivieren (Einstellung ändern) und "
      "eine Entscheidung herbeiführen (Handeln auslösen).",
 "e": "Präsentationsziel immer vom Adressaten her formulieren: Was soll er danach "
      "wissen, können, tun?"
},
"OK|12. November 2025|4|b": {
 "a": "Die Verständlichkeit einer Präsentation hängt vor allem von vier Aspekten "
      "ab (Hamburger Verständlichkeitsmodell):\n\n"
      "1. Einfachheit der Sprache: kurze, klare Sätze, geläufige Wörter, "
      "Fachbegriffe und Abkürzungen erklären. Für eine gemischte Zuhörerschaft aus "
      "Werkstatt, Fahrdienst und Verwaltung ist das entscheidend.\n\n"
      "2. Gliederung und Ordnung: erkennbarer roter Faden mit Agenda, sinnvoller "
      "Reihenfolge, sichtbaren Übergängen und einer Zusammenfassung am Schluss. "
      "Der Zuhörer muss jederzeit wissen, wo er sich befindet.\n\n"
      "3. Kürze und Prägnanz: Beschränkung auf das Wesentliche, keine Textwüsten "
      "auf den Folien, Stichworte statt ganzer Sätze, angemessene Zahl von Folien "
      "für die verfügbare Zeit.\n\n"
      "4. Anregende Zusätze und Gestaltung: Bilder, Diagramme, Schaubilder und "
      "Praxisbeispiele aus dem eigenen Betrieb; dazu lesbare Schriftgröße, "
      "ausreichender Kontrast und ein einheitliches Layout.\n\n"
      "Über allem steht der Adressatenbezug: Vorwissen, Erwartungen und Interessen "
      "der Zuhörer bestimmen, wie tief und in welcher Sprache präsentiert wird.",
 "e": "Vier Säulen der Verständlichkeit: Einfachheit, Gliederung, Kürze, "
      "anregende Zusätze."
},

"OK|12. November 2025|5|a": {
 "a": "Drei Maßnahmen zur Ermittlung des Qualifikationsbedarfs:\n\n"
      "1. Soll-Ist-Vergleich über Anforderungsprofile und Qualifikationsmatrix: "
      "Für jede Stelle wird das erforderliche Qualifikationsprofil festgelegt und "
      "dem tatsächlichen Kenntnisstand gegenübergestellt. Die Lücken sind der "
      "Qualifikationsbedarf – zugleich wird sichtbar, wo Vertretungen fehlen.\n\n"
      "2. Strukturierte Mitarbeiter- und Zielvereinbarungsgespräche: Im jährlichen "
      "Gespräch werden Entwicklungsstand, Stärken, Schwächen und Weiterbildungs"
      "wünsche besprochen und verbindliche Qualifizierungsziele vereinbart. Das "
      "erhöht zugleich die Akzeptanz der Maßnahmen.\n\n"
      "3. Auswertung betrieblicher Kennzahlen und Prüfergebnisse: Interne und "
      "externe Auditfeststellungen, Reklamationen, Fehler- und Schadensstatistiken "
      "sowie Kontrollbeanstandungen zeigen objektiv, an welchen Stellen Wissen oder "
      "Können fehlt und die Qualitätsziele gefährdet sind.\n\n"
      "Ergänzend liefern Arbeitsplatzbeobachtungen, Mitarbeiterbefragungen sowie "
      "absehbare Veränderungen – neue Technik, neue Rechtslage, altersbedingte "
      "Abgänge – weiteren Bedarf.",
 "e": "Bedarf immer aus drei Richtungen ermitteln: Soll-Ist-Abgleich, Gespräch, "
      "harte Kennzahlen."
},
"OK|12. November 2025|5|b": {
 "a": "Eine Qualifikationsmatrix (auch Kompetenz- oder Skill-Matrix) ist eine "
      "Tabelle, die Mitarbeiter und Tätigkeiten beziehungsweise geforderte "
      "Qualifikationen gegenüberstellt. In den Zeilen stehen die Mitarbeiter, in "
      "den Spalten die Tätigkeitsbereiche; in den Feldern wird der Beherrschungs"
      "grad eingetragen. Sie zeigt auf einen Blick, wer was kann, wo "
      "Qualifikationslücken bestehen, wo Vertretungsrisiken liegen (nur ein "
      "Mitarbeiter beherrscht eine Tätigkeit) und welche Schulungen zu planen sind. "
      "Zugleich ist sie ein Nachweis der Kompetenzsteuerung nach DIN EN ISO 9001.\n\n"
      "Bewertungsstufen: 0 = keine Kenntnisse · 1 = angelernt, arbeitet unter "
      "Anleitung · 2 = beherrscht die Tätigkeit selbstständig · 3 = beherrscht sie "
      "sicher und kann andere anleiten\n\n"
      "Beispielhafte Matrix für die Werkstatt (drei Tätigkeitsbereiche):\n\n"
      "Mitarbeiter | Bremsenprüfung und HU-Vorbereitung (§ 29 StVZO) | "
      "Arbeiten an Hochvoltsystemen (E-Busse) | Klimaanlagenwartung (Sachkunde "
      "F-Gase)\n"
      "Müller (Werkstattmeister) | 3 | 2 | 2\n"
      "Schmitz (Kfz-Mechatroniker) | 2 | 1 | 3\n"
      "Yilmaz (Kfz-Mechatroniker) | 2 | 0 | 0\n"
      "Auszubildender Weber | 1 | 0 | 0\n\n"
      "Auswertung: Beim Hochvolt-Bereich beherrscht nur ein Mitarbeiter die "
      "Tätigkeit selbstständig – hier besteht sowohl Qualifizierungs- als auch "
      "Vertretungsbedarf, zumal die Umstellung auf alternative Antriebe ansteht.",
 "e": "Die Matrix macht drei Dinge sichtbar: Lücken, Vertretungsrisiken und "
      "Schulungsbedarf."
},
"OK|12. November 2025|5|c": {
 "a": "Aufbau des Teilnehmer-Fragebogens (Evaluation einer Weiterbildung nach "
      "BKrFQG)\n\n"
      "Kopfteil: Bezeichnung der Maßnahme (z. B. „Kenntnisbereich 1 – "
      "Wirtschaftliche Fahrweise“), Datum, Dauer, Name des Dozenten, Hinweis auf "
      "Anonymität und Verwendungszweck.\n\n"
      "Bewertungsteil mit einheitlicher Skala:\n"
      "1 = trifft voll zu · 2 = trifft überwiegend zu · 3 = teils/teils · "
      "4 = trifft eher nicht zu · 5 = trifft nicht zu\n\n"
      "Vier Auswertungskriterien mit je einer Aussage zum Ankreuzen:\n\n"
      "1. Fachliche Qualität und Kompetenz des Dozenten – „Der Referent war "
      "fachlich sicher und konnte Fragen aus der Praxis beantworten.“ (1–5)\n\n"
      "2. Praxisbezug und Anwendbarkeit – „Die Inhalte kann ich in meinem "
      "Fahralltag unmittelbar anwenden.“ (1–5)\n\n"
      "3. Verständlichkeit der Vermittlung und Medieneinsatz – „Die Inhalte wurden "
      "verständlich dargestellt, die eingesetzten Medien und Unterlagen waren "
      "hilfreich.“ (1–5)\n\n"
      "4. Organisation und Rahmenbedingungen – „Räumlichkeiten, Zeitplanung, "
      "Gruppengröße und Pausen waren angemessen.“ (1–5)\n\n"
      "Freitextteil: „Was war besonders hilfreich?“, „Was sollte verbessert "
      "werden?“, „Welche Themen wünschen Sie sich für die nächste Weiterbildung?“\n\n"
      "Auswertung: Je Kriterium wird der Mittelwert gebildet und über die Jahre "
      "sowie über Dozenten hinweg verglichen. Werte ab 3,0 lösen eine konkrete "
      "Maßnahme aus (Gespräch mit dem Dozenten, Anpassung der Inhalte, Wechsel des "
      "Bildungsträgers). Die Ergebnisse fließen dokumentiert in die "
      "Managementbewertung des Qualitätsmanagements ein.",
 "e": "Ein brauchbarer Feedbackbogen braucht: eindeutige Skala, wenige klare "
      "Kriterien, Freitext und eine feste Konsequenz aus dem Ergebnis."
},

"OK|12. November 2025|6|a": {
 "a": "Linie 910\n"
      "Wagenkilometer gesamt: 2 Busse × 67.000 km = 134.000 km\n"
      "Nutzkilometer (abzüglich 3 % Leerkilometer): 134.000 km × 0,97 = 129.980 km\n"
      "Nutzplatzkilometer: 129.980 km × 50 Plätze = 6.499.000 Platz-km\n"
      "Jährliche Linienkosten: 134.000 km × 2,10 €/km = 281.400,00 €\n\n"
      "Linie 920\n"
      "Nettoarbeitsstunden je Fahrer: (2.200 h − 225 h Urlaub) = 1.975 h; "
      "abzüglich 10 % Fehlzeiten: 1.975 h × 0,9 = 1.777,5 h\n"
      "Gesamte Fahrdienststunden: 1.777,5 h × 5,1 Mitarbeiter = 9.065,25 h\n"
      "Wagenkilometer gesamt: 9.065,25 h × 18 km/h = 163.174,50 km\n"
      "Nutzkilometer (abzüglich 4.000 km Leerkilometer): 159.174,50 km\n"
      "Nutzplatzkilometer: 159.174,50 km × 45 Plätze = 7.162.852,50 Platz-km\n"
      "Jährliche Linienkosten: 163.174,50 km × 1,95 €/km = 318.190,28 €\n\n"
      "Zusammenfassung: Linie 910 erbringt 6.499.000 Nutzplatzkilometer bei "
      "281.400,00 € Kosten, Linie 920 erbringt 7.162.852,50 Nutzplatzkilometer bei "
      "318.190,28 € Kosten. Bezogen auf die Leistungseinheit kostet Linie 910 rund "
      "4,33 Cent und Linie 920 rund 4,44 Cent je 1.000 Nutzplatzkilometer – "
      "Linie 910 arbeitet damit geringfügig günstiger.",
 "e": "Achtung: Die Linienkosten werden auf ALLE Wagenkilometer gerechnet "
      "(auch Leerkilometer), die Nutzplatzkilometer nur auf die Nutzkilometer."
},


# ══════ Fuhrparktechnik und Fuhrparkmanagement · 11. November 2025 ══════


"FT|11. November 2025|1|a": {
 "a": "Lückenloser Arbeitszeitnachweis bedeutet, dass für jeden einzelnen Tag "
      "des mitzuführenden Zeitraums nachgewiesen werden kann, womit der Fahrer "
      "diesen Tag verbracht hat – ohne jede Lücke. Erfasst werden nicht nur "
      "Lenkzeiten, sondern auch sonstige Arbeitszeiten, Bereitschaftszeiten und "
      "Ruhezeiten. Auch Tage ohne Fahrtätigkeit (Urlaub, Krankheit, "
      "Ausgleichsruhezeit, Tätigkeit auf einem Fahrzeug ohne Fahrtenschreiber) "
      "müssen belegt sein – entweder durch manuelle Nachträge auf der Fahrerkarte "
      "oder durch eine entsprechende Bescheinigung. Beim digitalen Fahrtenschreiber "
      "erfolgt das über das Einstecken der Fahrerkarte, die manuelle Nachtragung "
      "beim Kartenwechsel und die korrekte Bedienung der Zeitgruppenschalter.\n\n"
      "Zwei gesetzliche Vorgaben:\n\n"
      "1. Art. 36 VO (EU) Nr. 165/2014: Der Fahrer muss die Fahrerkarte sowie "
      "alle handschriftlichen Aufzeichnungen, Ausdrucke und Bescheinigungen des "
      "laufenden Tages und der vorausgegangenen 56 Kalendertage mitführen und auf "
      "Verlangen vorlegen. (Der Zeitraum wurde zum 31.12.2024 von 28 auf 56 Tage "
      "erweitert.)\n\n"
      "2. § 21a Abs. 7 ArbZG in Verbindung mit § 16 Abs. 2 ArbZG: Der Arbeitgeber "
      "muss die Arbeitszeit der Fahrer aufzeichnen und die Aufzeichnungen "
      "mindestens zwei Jahre aufbewahren; der Fahrer erhält auf Verlangen eine "
      "Kopie. Ergänzend verlangt Art. 34 VO (EU) 165/2014 die manuelle Nachtragung "
      "von Zeiten, die das Gerät nicht aufzeichnen konnte.",
 "e": "Lückenlos heißt: kein Tag ohne Nachweis – auch Urlaub und Krankheit müssen "
      "belegt werden. Mitführpflicht: laufender Tag + 56 Kalendertage."
},
"FT|11. November 2025|1|b": {
 "a": "Lenkzeit\n"
      "1. Lenkzeit ist die Zeit, in der der Fahrer das Fahrzeug tatsächlich führt; "
      "sie wird vom digitalen Kontrollgerät automatisch erfasst, sobald sich das "
      "Fahrzeug bewegt.\n"
      "2. Sie ist nach VO (EG) 561/2006 streng begrenzt: höchstens 9 Stunden "
      "täglich, zweimal wöchentlich 10 Stunden, höchstens 56 Stunden je Woche und "
      "90 Stunden in zwei aufeinanderfolgenden Wochen.\n"
      "3. Nach spätestens 4,5 Stunden Lenkzeit ist eine Fahrtunterbrechung von "
      "45 Minuten einzulegen (teilbar in 15 + 30 Minuten in dieser Reihenfolge).\n\n"
      "Arbeitszeit\n"
      "1. Arbeitszeit umfasst alle Tätigkeiten außer dem Lenken, die zur Erfüllung "
      "der beruflichen Aufgaben gehören – Be- und Entladen, Ladungssicherung, "
      "Reinigung, technische Wartung, Hilfeleistung beim Ein- und Aussteigen von "
      "Fahrgästen, behördliche Formalitäten.\n"
      "2. Sie wird über den Zeitgruppenschalter des Kontrollgeräts erfasst "
      "(Symbol „Hammer“) und zählt zur Arbeitszeit im Sinne des ArbZG.\n"
      "3. Die durchschnittliche Wochenarbeitszeit darf 48 Stunden nicht "
      "überschreiten; in einer einzelnen Woche sind bis zu 60 Stunden zulässig, "
      "wenn im Ausgleichszeitraum von vier Monaten der Durchschnitt eingehalten "
      "wird (§ 21a ArbZG).\n\n"
      "Bereitschaftszeit\n"
      "1. Bereitschaftszeit ist Wartezeit, deren voraussichtliche Dauer dem Fahrer "
      "im Voraus bekannt ist und in der er sich nicht am Arbeitsplatz aufhalten, "
      "wohl aber verfügbar sein muss – etwa Wartezeit an der Rampe oder auf der "
      "Fähre, ebenso die Zeit als Beifahrer im Mehrfahrerbetrieb.\n"
      "2. Sie wird mit dem Symbol „Kasten“ (Bereitschaft) eingestellt und getrennt "
      "aufgezeichnet.\n"
      "3. Bereitschaftszeit zählt nach § 21a Abs. 3 ArbZG nicht als Arbeitszeit, "
      "ist aber auch keine Ruhezeit – sie darf also nicht auf die tägliche Ruhezeit "
      "angerechnet werden.",
 "e": "Die drei Zeitarten sauber trennen: Lenken = Fahrzeug bewegt, Arbeit = alles "
      "andere Tun, Bereitschaft = Warten mit im Voraus bekannter Dauer."
},
"FT|11. November 2025|1|c": {
 "a": "Inhalt der Verordnung (EU) Nr. 165/2014 (Kontrollgeräteverordnung)\n\n"
      "Sie regelt den Fahrtenschreiber im Straßenverkehr in technischer und "
      "verfahrensrechtlicher Hinsicht: Bauart, Zulassung, Einbau, Prüfung und "
      "Benutzung der Kontrollgeräte, die Ausgabe und Verwendung der Fahrer-, "
      "Unternehmens-, Werkstatt- und Kontrollkarten sowie die Durchführung der "
      "Kontrollen. Sie ist damit das Instrument, mit dem die Einhaltung der "
      "Sozialvorschriften der VO (EG) 561/2006 überhaupt überprüfbar wird; die "
      "561/2006 regelt die Zeiten selbst, die 165/2014 deren Aufzeichnung und "
      "Nachweis. Sie schreibt außerdem die stufenweise Einführung des intelligenten "
      "Fahrtenschreibers vor.\n\n"
      "Vier Unternehmerpflichten aus dieser Verordnung:\n\n"
      "1. Ausrüstungs- und Prüfpflicht: Der Unternehmer muss seine Fahrzeuge mit "
      "einem vorschriftsmäßigen, geeichten Kontrollgerät ausrüsten und dieses "
      "mindestens alle zwei Jahre in einer anerkannten Werkstatt prüfen lassen "
      "(Art. 23).\n\n"
      "2. Auslese-, Speicher- und Aufbewahrungspflicht: Die Daten des "
      "Massenspeichers sind mindestens alle 90 Tage, die der Fahrerkarte "
      "mindestens alle 28 Tage auszulesen, zu speichern und mindestens ein Jahr "
      "aufzubewahren sowie den Kontrollbehörden auf Verlangen vorzulegen "
      "(Art. 33, 36).\n\n"
      "3. Schulungs- und Ausstattungspflicht: Der Unternehmer muss die Fahrer in "
      "der ordnungsgemäßen Bedienung des Kontrollgeräts unterweisen, regelmäßig "
      "kontrollieren und sie mit ausreichend Druckerpapier beziehungsweise "
      "Schaublättern ausstatten (Art. 33).\n\n"
      "4. Überwachungs- und Abstellpflicht: Er hat die ausgelesenen Daten auf "
      "Verstöße zu prüfen, festgestellte Verstöße abzustellen und ihre "
      "Wiederholung zu verhindern. Ergänzend verbietet Art. 10 VO (EG) 561/2006, "
      "die Vergütung so zu gestalten (Prämien nach Strecke oder Menge), dass sie "
      "zu Verstößen verleitet.",
 "e": "Merken: 561/2006 regelt die Zeiten, 165/2014 das Gerät und den Nachweis. "
      "Auslesen: Fahrerkarte alle 28 Tage, Massenspeicher alle 90 Tage."
},

"FT|11. November 2025|2|a": {
 "a": "Erforderliche Sicherungskräfte\n\n"
      "Ladungsgewicht: 16 Paletten × 1.000 kg = 16.000 kg\n"
      "Gewichtskraft: F_G = m × g = 16.000 kg × 9,81 m/s² = 156.960 N ≈ 156,96 kN "
      "(15.696 daN)\n\n"
      "Nach VDI 2700 / DIN EN 12195-1 sind zu sichern:\n"
      "– nach vorn: 0,8 × F_G = 125.568 N ≈ 125,6 kN\n"
      "– nach hinten: 0,5 × F_G = 78.480 N ≈ 78,5 kN\n"
      "– zur Seite: 0,5 × F_G = 78.480 N ≈ 78,5 kN\n\n"
      "Beitrag der Reibung\n"
      "Mit rutschhemmendem Material ist ein Gleitreibbeiwert von μ = 0,6 "
      "anzusetzen (Nachweis über das Prüfzeugnis des Materials erforderlich):\n"
      "F_R = μ × F_G = 0,6 × 156.960 N = 94.176 N ≈ 94,2 kN\n\n"
      "Bewertung je Richtung\n\n"
      "Nach vorn: erforderlich 125,6 kN, durch Reibung gedeckt 94,2 kN. "
      "Es verbleibt eine zu sichernde Restkraft von 125.568 N − 94.176 N = "
      "31.392 N ≈ 31,4 kN (3.139 daN). Die Ladung ist formschlüssig gegen die "
      "Stirnwand geladen. Der Sattelauflieger ist nach DIN EN 12642 in "
      "Code-L-Ausführung gebaut; die Stirnwand nimmt 0,4 der Nutzlast auf, "
      "begrenzt auf 5.000 daN. Erforderlich sind 3.139 daN – die Stirnwand hält "
      "diese Kraft aus. Die Sicherung nach vorn ist damit gegeben.\n\n"
      "Nach hinten und zur Seite: erforderlich jeweils 78,5 kN, allein durch die "
      "Reibung stehen 94,2 kN zur Verfügung. Die Ladung ist zudem als standsicher "
      "beschrieben, kippt also nicht. Auch hier ist die Sicherung rechnerisch "
      "erfüllt.\n\n"
      "Ergebnis: Die vom Fahrer getroffenen Maßnahmen – formschlüssige Verladung "
      "an der Stirnwand, rutschhemmendes Material und zusätzlich je ein Gurtpaar "
      "als Niederzurrung – reichen rechnerisch aus. Die Niederzurrungen erhöhen "
      "die Anpresskraft und damit die Reibung zusätzlich, sind also eine Reserve "
      "über das erforderliche Maß hinaus. Der Widerspruch ist insoweit begründet.\n\n"
      "Wichtige Einschränkung für die Stellungnahme: Der Reibbeiwert von μ = 0,6 "
      "muss durch das Prüfzeugnis des verwendeten rutschhemmenden Materials "
      "belegt werden. Ohne diesen Nachweis ist bei der Paarung Holz auf "
      "Siebdruckplatte nur μ = 0,3 anzusetzen; dann verbliebe nach vorn eine "
      "Restkraft von 0,8 × F_G − 0,3 × F_G = 78.480 N (7.848 daN), die die "
      "Code-L-Stirnwand mit 5.000 daN nicht mehr aufnehmen könnte. Dem "
      "Widerspruch sind daher das Prüfzeugnis des rutschhemmenden Materials und "
      "die Zertifikate der Zurrmittel beizufügen.",
 "e": "Sicherungskräfte: vorn 0,8 × F_G, hinten und seitlich 0,5 × F_G. Die "
      "Reibung darf gegengerechnet werden – aber nur mit nachgewiesenem μ."
},
"FT|11. November 2025|2|b": {
 "a": "Gesamtschwerpunkt der Ladung\n\n"
      "Die 16 Europaletten sind einreihig und formschlüssig geladen. Bei "
      "Querstellung beansprucht jede Palette 0,80 m in Fahrtrichtung:\n"
      "16 × 0,80 m = 12,80 m Ladelänge bei einer Ladefläche von 13,60 m.\n\n"
      "Da alle Paletten gleich schwer sind (je 1.000 kg) und ihr Schwerpunkt "
      "jeweils mittig liegt, ist die Last gleichmäßig verteilt. Der "
      "Gesamtschwerpunkt liegt damit in der Mitte der Ladelänge, gemessen von der "
      "Stirnwand:\n\n"
      "x_S = 12,80 m ÷ 2 = 6,40 m hinter der Stirnwand\n\n"
      "Rechnerisch über die Momentensumme bestätigt: Die Palettenschwerpunkte "
      "liegen bei 0,40 m; 1,20 m; 2,00 m … 12,40 m. Die Summe dieser Abstände "
      "beträgt 102,40 m; geteilt durch 16 Paletten ergibt das ebenfalls 6,40 m.\n\n"
      "Begründung anhand des Lastverteilungsplans\n\n"
      "Im Lastverteilungsplan des Aufliegers ist auf der waagerechten Achse der "
      "Abstand des Ladungsschwerpunkts von der Stirnwand aufgetragen, auf der "
      "senkrechten Achse die dort höchstzulässige Last. Die Kurve steigt von der "
      "Stirnwand an, erreicht ihr Maximum von etwa 25 t im Bereich zwischen 6 m "
      "und 8 m und fällt danach steil ab.\n\n"
      "Der ermittelte Schwerpunkt von 6,40 m liegt genau in diesem Höchstbereich. "
      "Die tatsächliche Ladung wiegt 16 t und bleibt damit deutlich unter der dort "
      "zulässigen Last von rund 25 t. Die Lastverteilung ist folglich zulässig – "
      "die Achslasten der Sattelzugmaschine und des Aufliegers werden eingehalten. "
      "Auch die Gesamtmasse ist unkritisch: 8 t Leergewicht Zugmaschine + 7 t "
      "Leergewicht Auflieger + 16 t Ladung = 31 t bei zulässigen 40 t für das "
      "fünfachsige Sattelkraftfahrzeug.\n\n"
      "Für die Stellungnahme folgt daraus: Der Vorwurf der mangelhaften "
      "Lastverteilung lässt sich anhand des Lastverteilungsplans widerlegen. "
      "Beizufügen sind der Lastverteilungsplan, ein Wiegeschein und die "
      "Ladeliste mit der Palettenanordnung.",
 "e": "Bei gleichmäßig verteilter Ladung liegt der Schwerpunkt in der Mitte der "
      "Ladelänge – im Lastverteilungsplan dann die zulässige Last ablesen."
},

"FT|11. November 2025|3|a": {
 "a": "Der PDCA-Zyklus (auch Deming-Kreis) ist das Grundmodell des "
      "kontinuierlichen Verbesserungsprozesses. Er beschreibt Verbesserung nicht "
      "als einmaliges Projekt, sondern als immer wiederkehrenden Kreislauf aus "
      "vier Phasen. Nach jedem Durchlauf beginnt der Zyklus auf dem erreichten, "
      "höheren Niveau von Neuem – das Rad rollt aufwärts und wird durch die "
      "Standardisierung gegen Zurückrollen gesichert. In der DIN EN ISO 9001 ist "
      "dieses Denken als prozessorientierter Ansatz fest verankert.\n\n"
      "Die vier Phasen:\n\n"
      "1. Plan (Planen): Der Ist-Zustand wird analysiert, das Problem und seine "
      "Ursachen werden ermittelt, messbare Ziele werden festgelegt und Maßnahmen "
      "geplant. Hier wird auch bestimmt, woran der Erfolg später gemessen wird.\n\n"
      "2. Do (Durchführen): Die geplanten Maßnahmen werden zunächst im kleinen "
      "Rahmen erprobt – als Test, Pilot oder in einem begrenzten Bereich. Damit "
      "bleibt das Risiko überschaubar und Erkenntnisse können noch einfließen.\n\n"
      "3. Check (Prüfen): Die Ergebnisse werden mit den in der Planungsphase "
      "gesetzten Zielen verglichen. Anhand von Kennzahlen wird bewertet, ob die "
      "Maßnahme gewirkt hat, teilweise gewirkt hat oder wirkungslos war.\n\n"
      "4. Act (Handeln): Hat sich die Maßnahme bewährt, wird sie zum verbindlichen "
      "Standard erhoben, dokumentiert und auf alle betroffenen Bereiche "
      "ausgeweitet; die Mitarbeiter werden geschult. Hat sie nicht gewirkt, "
      "beginnt der Zyklus mit einer neuen Planung von vorn.",
 "e": "Plan – Do – Check – Act. Entscheidend ist das „Act“: Ohne Standardisierung "
      "fällt der Betrieb in alte Gewohnheiten zurück."
},
"FT|11. November 2025|3|b": {
 "a": "PDCA am Beispiel der Ersatzteilbeschaffung für das Werkstattlager\n\n"
      "Ausgangslage: In der Werkstatt kommt es wiederholt zu Standzeiten, weil "
      "benötigte Ersatzteile nicht vorrätig sind. Gleichzeitig liegen Teile über "
      "Monate unbewegt im Lager und binden Kapital.\n\n"
      "1. Plan (Planen)\n"
      "Der Ist-Zustand wird erhoben: Auswertung der Lagerbestände, der "
      "Umschlagshäufigkeit je Artikel, der Fehlmengen und der dadurch "
      "entstandenen Fahrzeugstandzeiten. Eine ABC-Analyse trennt die wenigen "
      "wertintensiven A-Teile von den vielen geringwertigen C-Teilen. Als Ziele "
      "werden festgelegt: Fehlmengenquote unter 2 %, Erhöhung der "
      "Umschlagshäufigkeit von 10 auf 12, Senkung des durchschnittlichen "
      "Lagerbestands um 15 %. Geplante Maßnahmen: Meldebestände und optimale "
      "Bestellmengen je Artikel berechnen, Rahmenvertrag mit dem Hauptlieferanten "
      "über 24-Stunden-Lieferung für B- und C-Teile, wöchentlicher Bestellrhythmus "
      "statt monatlicher Sammelbestellung.\n\n"
      "2. Do (Durchführen)\n"
      "Die Maßnahmen werden zunächst nur für eine abgegrenzte Warengruppe erprobt "
      "– beispielsweise Leuchtmittel, Filter und Bremsbeläge. Für diese Artikel "
      "werden Meldebestand und optimale Bestellmenge im Lagerprogramm hinterlegt, "
      "die Lagerorte gekennzeichnet und die Werkstattmitarbeiter unterwiesen, "
      "jede Entnahme sofort zu buchen. Der Pilot läuft über drei Monate.\n\n"
      "3. Check (Prüfen)\n"
      "Nach dem Pilotzeitraum werden die Kennzahlen erneut erhoben und mit den "
      "Zielwerten verglichen: Wie oft musste eine Reparatur wegen fehlender Teile "
      "verschoben werden? Wie hoch sind Umschlagshäufigkeit, durchschnittliche "
      "Lagerdauer und gebundenes Kapital jetzt? Sind die Bestell- und "
      "Lagerhaltungskosten insgesamt gesunken? Abweichungen werden auf ihre "
      "Ursachen untersucht – etwa nicht gebuchte Entnahmen, die den Bestand "
      "verfälschen.\n\n"
      "4. Act (Handeln)\n"
      "Bewährt sich das Vorgehen, wird es zum Standard: Die Regeln werden als "
      "Verfahrensanweisung „Ersatzteilbeschaffung und Lagerhaltung“ in das "
      "Qualitätsmanagementsystem aufgenommen, auf das gesamte Sortiment "
      "ausgeweitet, alle Mitarbeiter werden geschult, und die Kennzahlen werden "
      "künftig monatlich überwacht. Zeigt der Vergleich dagegen, dass die Ziele "
      "verfehlt wurden, beginnt der Zyklus mit einer neuen Analyse – etwa der "
      "Frage, ob ein Konsignationslager des Lieferanten die bessere Lösung ist.",
 "e": "Immer am konkreten Beispiel zeigen: messbare Ziele in „Plan“, kleiner "
      "Pilot in „Do“, Kennzahlenvergleich in „Check“, Standardisierung in „Act“."
},

"FT|11. November 2025|4|a": {
 "a": "Zunächst wird der Jahresverbrauch über die Bestandsfortschreibung "
      "ermittelt:\n\n"
      "Zugänge: Januar bis Juni 6 × 710 Stück = 4.260 Stück; Juli bis Oktober "
      "4 × 625 Stück = 2.500 Stück; November und Dezember keine Bestellung.\n"
      "Zugänge gesamt: 4.260 + 2.500 = 6.760 Stück\n\n"
      "Jahresverbrauch = Anfangsbestand + Zugänge − Endbestand\n"
      "= 820 + 6.760 − 580 = 7.000 Stück\n\n"
      "Durchschnittlicher Lagerbestand = (Anfangsbestand + Endbestand) ÷ 2\n"
      "= (820 + 580) ÷ 2 = 700 Stück\n\n"
      "Umschlagshäufigkeit = Jahresverbrauch ÷ durchschnittlicher Lagerbestand\n"
      "= 7.000 ÷ 700 = 10\n\n"
      "Durchschnittliche Lagerdauer = 360 Tage ÷ Umschlagshäufigkeit\n"
      "= 360 ÷ 10 = 36 Tage\n\n"
      "Die Leuchtmittel liegen also im Mittel 36 Tage im Lager, bevor sie "
      "entnommen werden.",
 "e": "Reihenfolge merken: Verbrauch → Ø-Bestand → Umschlagshäufigkeit → "
      "Lagerdauer (360 ÷ Umschlagshäufigkeit)."
},
"FT|11. November 2025|4|b": {
 "a": "Die optimale Bestellmenge ergibt sich aus der Andlerschen Formel. Sie "
      "sucht den Punkt, an dem die Summe aus Bestellkosten und "
      "Lagerhaltungskosten am geringsten ist: Je größer die Bestellmenge, desto "
      "seltener wird bestellt (weniger Bestellkosten), desto höher ist aber der "
      "Lagerbestand (mehr Lagerkosten).\n\n"
      "q_opt = √( 200 × Jahresbedarf × Bestellkosten je Bestellung ÷ "
      "(Einstandspreis × Lagerhaltungskostensatz) )\n\n"
      "Eingesetzt:\n"
      "q_opt = √( 200 × 7.000 × 120 € ÷ (12 €/Stück × 14) )\n"
      "q_opt = √( 168.000.000 ÷ 168 )\n"
      "q_opt = √1.000.000\n"
      "q_opt = 1.000 Stück\n\n"
      "Die optimale Bestellmenge beträgt 1.000 Stück. Bei einem Jahresbedarf von "
      "7.000 Stück wären damit 7 Bestellungen im Jahr zu tätigen, also etwa alle "
      "sieben bis acht Wochen eine Bestellung.",
 "e": "Die 200 in der Formel entsteht aus 2 × 100, weil der "
      "Lagerhaltungskostensatz in Prozent eingesetzt wird."
},
"FT|11. November 2025|4|c": {
 "a": "Bestellkosten\n"
      "Anzahl der Bestellungen = Jahresbedarf ÷ optimale Bestellmenge\n"
      "= 7.000 ÷ 1.000 = 7 Bestellungen\n"
      "Bestellkosten = 7 × 120 € = 840,00 €\n\n"
      "Lagerhaltungskosten\n"
      "Grundlage ist der in Teilaufgabe a) ermittelte durchschnittliche "
      "Lagerbestand von 700 Stück:\n"
      "Lagerhaltungskosten = 700 Stück × 12 €/Stück × 14 %\n"
      "= 8.400 € × 0,14 = 1.176,00 €\n\n"
      "Gesamtkosten\n"
      "Gesamtkosten = Bestellkosten + Lagerhaltungskosten\n"
      "= 840,00 € + 1.176,00 € = 2.016,00 €\n\n"
      "Bewertung: Im theoretischen Optimum der Andler-Formel wird unterstellt, "
      "dass der Lagerbestand gleichmäßig von der Bestellmenge auf null absinkt; "
      "der durchschnittliche Bestand betrüge dann nur 1.000 ÷ 2 = 500 Stück und "
      "die Lagerhaltungskosten ebenfalls 840,00 € – Bestell- und Lagerkosten wären "
      "gleich hoch, die Gesamtkosten lägen bei 1.680,00 €.\n\n"
      "Der tatsächliche durchschnittliche Bestand liegt mit 700 Stück um 200 Stück "
      "darüber. Darin liegt das gesuchte Optimierungspotenzial: Durch einen zu "
      "hohen Sicherheitsbestand werden jährlich rund 336 € unnötige "
      "Lagerhaltungskosten verursacht und zusätzlich Kapital gebunden. Ansatzpunkte "
      "sind ein niedrigerer Meldebestand, kürzere Lieferzeiten über einen "
      "Rahmenvertrag und eine gleichmäßigere Bestellung über das Jahr – im "
      "Betrachtungsjahr wurde in November und Dezember gar nicht bestellt, was auf "
      "eine unregelmäßige Disposition hindeutet.",
 "e": "Im Optimum sind Bestellkosten und Lagerhaltungskosten gleich hoch – weicht "
      "der Ist-Bestand davon ab, liegt dort das Einsparpotenzial."
},

"FT|11. November 2025|5|a": {
 "a": "Zwei Nachteile einer internen Stellenbesetzung:\n\n"
      "1. Fehlende neue Impulse und Betriebsblindheit: Wer die Stelle intern "
      "besetzt, holt niemanden mit fremder Erfahrung ins Unternehmen. Eingefahrene "
      "Abläufe und Denkmuster werden fortgeschrieben, statt hinterfragt zu werden. "
      "Gerade bei anstehenden Veränderungen – alternative Antriebe, Digitalisierung "
      "der Disposition, Weiterentwicklung des Qualitätsmanagements – fehlt dann "
      "der Blick von außen.\n\n"
      "2. Folgeprobleme im Personalgefüge: Die intern besetzte Stelle reißt an "
      "anderer Stelle eine neue Lücke, sodass eine Kette von Nachbesetzungen "
      "entsteht – das eigentliche Problem der altersbedingten Abgänge wird nur "
      "verschoben. Hinzu kommen Enttäuschung und Motivationsverlust bei den "
      "übergangenen Bewerbern sowie mögliche Spannungen im Team, wenn ein "
      "bisheriger Kollege nun Vorgesetzter ist. Auch die Auswahl ist eingeschränkt, "
      "weil nur aus einem kleinen Kreis geschöpft werden kann.",
 "e": "Interne Besetzung spart Einarbeitung, bringt aber keine frischen Ideen und "
      "verschiebt die Lücke nur."
},
"FT|11. November 2025|5|b": {
 "a": "Ein Assessment-Center macht Verhalten sichtbar, das sich aus Zeugnissen "
      "und einem Vorstellungsgespräch nicht zuverlässig ablesen lässt. Beobachtbar "
      "sind insbesondere folgende drei Anforderungen:\n\n"
      "1. Kommunikationsfähigkeit: Wie verständlich, strukturiert und "
      "adressatengerecht drückt sich der Bewerber aus? Hört er zu, geht er auf "
      "Einwände ein, kann er auch unangenehme Sachverhalte sachlich vermitteln? "
      "Für eine Position mit Kontakt zu Fahrpersonal, Werkstatt, Kunden und "
      "Behörden ist das eine Kernanforderung.\n\n"
      "2. Konflikt- und Kritikfähigkeit: Wie verhält sich der Bewerber unter "
      "Spannung? Bleibt er sachlich, trennt er Sach- und Beziehungsebene, sucht er "
      "eine tragfähige Lösung oder setzt er sich nur durch? Im Fuhrpark ist das "
      "täglich gefragt – etwa bei Beanstandungen gegenüber Fahrern oder bei "
      "Terminkonflikten mit der Disposition.\n\n"
      "3. Entscheidungs- und Problemlösefähigkeit unter Zeitdruck: Erfasst der "
      "Bewerber schnell die wesentlichen Informationen, setzt er Prioritäten, "
      "trifft er nachvollziehbare Entscheidungen und begründet er sie? Gerade "
      "die Disposition verlangt tägliches Entscheiden bei unvollständiger "
      "Information.\n\n"
      "Ergänzend lassen sich Teamfähigkeit, Durchsetzungsvermögen und "
      "Belastbarkeit beobachten.",
 "e": "Im AC wird Verhalten beobachtet, nicht Wissen abgefragt – deshalb immer "
      "verhaltensnahe Anforderungen nennen."
},
"FT|11. November 2025|5|c": {
 "a": "Zwei geeignete Übungen:\n\n"
      "1. Gruppendiskussion (führerlose Diskussion)\n"
      "Merkmal 1 – Aufbau: Vier bis sechs Bewerber erhalten eine betriebsnahe "
      "Fragestellung, etwa „Nach welchen Kriterien soll der Fuhrpark auf "
      "alternative Antriebe umgestellt werden?“, und sollen in 30 bis 45 Minuten "
      "ohne bestimmten Gesprächsleiter zu einem gemeinsamen Ergebnis kommen. Die "
      "Beobachter greifen nicht ein.\n"
      "Merkmal 2 – Beobachtungsschwerpunkt: Sichtbar werden Kommunikations- und "
      "Konfliktfähigkeit sowie Teamverhalten. Bewertet wird anhand eines "
      "Beobachtungsbogens, ob jemand andere ausreden lässt, Argumente aufgreift, "
      "moderierend wirkt oder das Gespräch dominiert – und ob die Gruppe mit "
      "seiner Hilfe zum Ziel kommt.\n\n"
      "2. Postkorbübung\n"
      "Merkmal 1 – Aufbau: Der Bewerber übernimmt fiktiv die Rolle des "
      "Fuhrparkleiters und findet 15 bis 20 Vorgänge vor – Krankmeldung eines "
      "Fahrers, Reklamation eines Kunden, Werkstatttermin, Anruf der Behörde, "
      "private Nachricht. In begrenzter Zeit, meist 45 Minuten, muss er alles "
      "bearbeiten: erledigen, delegieren, terminieren oder zurückstellen.\n"
      "Merkmal 2 – Beobachtungsschwerpunkt: Sichtbar werden Entscheidungs- und "
      "Problemlösefähigkeit unter Zeitdruck sowie Prioritätensetzung und "
      "Delegationsverhalten. Im anschließenden Nachgespräch begründet der "
      "Bewerber seine Reihenfolge – das zeigt zugleich seine "
      "Kommunikationsfähigkeit.\n\n"
      "Beide Übungen decken damit genau die unter b) genannten Anforderungen ab. "
      "Wichtig für die Aussagekraft: mehrere geschulte Beobachter, ein "
      "einheitlicher Beobachtungsbogen und die Trennung von Beobachtung und "
      "Bewertung.",
 "e": "Gruppendiskussion zeigt soziales Verhalten, Postkorb zeigt Organisation "
      "und Entscheidung unter Zeitdruck."
},


# ══════════ Organisation und Kommunikation · 8. Mai 2025 ══════════


"OK|8. Mai 2025|1|a": {
 "a": "Auswertung der Nutzwertanalyse\n\n"
      "Für jedes Kriterium wird der Teilnutzwert aus Gewichtung × Punkte "
      "gebildet; die Summe der Teilnutzwerte ergibt den Gesamtnutzwert.\n\n"
      "Kriterium (Gewichtung) — Werkstatt A / B / C, jeweils Punkte → Teilnutzwert\n\n"
      "Verrechnungspreis (8): 60 → 480 | 80 → 640 | 70 → 560\n"
      "Qualität (9): 70 → 630 | 60 → 540 | 60 → 540\n"
      "Reparaturzeit (5): 100 → 500 | 40 → 200 | 60 → 300\n"
      "Termintreue (10): 90 → 900 | 70 → 700 | 40 → 400\n"
      "Technischer Support (5): 60 → 300 | 80 → 400 | 70 → 350\n"
      "Kaufmännischer Service (4): 50 → 200 | 50 → 200 | 60 → 240\n"
      "Entfernung Werkstatt (10): 80 → 800 | 70 → 700 | 80 → 800\n"
      "Know-how (7): 60 → 420 | 80 → 560 | 70 → 490\n\n"
      "Erreichte Punkte (Gesamtnutzwert):\n"
      "Werkstatt A = 4.230\n"
      "Werkstatt B = 3.940\n"
      "Werkstatt C = 3.680\n\n"
      "Rangfolge:\n"
      "Rang 1: Werkstatt A (4.230)\n"
      "Rang 2: Werkstatt B (3.940)\n"
      "Rang 3: Werkstatt C (3.680)\n\n"
      "Ergebnis: Werkstatt A erreicht den höchsten Nutzwert und ist damit zu "
      "empfehlen. Ausschlaggebend sind ihre Spitzenwerte bei den hoch "
      "gewichteten Kriterien Termintreue (Gewichtung 10, 90 Punkte) und "
      "Qualität (Gewichtung 9, 70 Punkte) sowie die volle Punktzahl bei der "
      "Reparaturzeit. Ihre Schwäche beim Verrechnungspreis (nur 60 Punkte) wird "
      "dadurch mehr als ausgeglichen – der Preis ist mit 8 geringer gewichtet "
      "als die Zuverlässigkeit.",
 "e": "Teilnutzwert = Gewichtung × Punkte. Immer alle Teilnutzwerte je Anbieter "
      "aufsummieren und anschließend die Rangfolge angeben."
},
"OK|8. Mai 2025|1|b": {
 "a": "Die Nutzwertanalyse bewertet nur die vorher festgelegten Kriterien. Für "
      "die endgültige Entscheidung sind darüber hinaus vor allem drei Punkte "
      "heranzuziehen:\n\n"
      "1. Wirtschaftliche Stabilität und Zuverlässigkeit des Anbieters: Über "
      "eine Bonitätsauskunft und Referenzen vergleichbarer Flotten ist zu "
      "prüfen, ob der Dienstleister dauerhaft leistungsfähig ist. Fällt die "
      "Werkstatt eines Vertragspartners aus, steht der Fuhrpark – die "
      "Instandhaltung wird schließlich vollständig ausgelagert.\n\n"
      "2. Vertragliche Konditionen im Detail: Zu klären sind garantierte "
      "Reaktions- und Bereitstellungszeiten (auch nachts und am Wochenende), "
      "Gewährleistungs- und Haftungsregelungen, Preisanpassungsklauseln, "
      "Vertragslaufzeit und Kündigungsfristen sowie die Frage, ob Hol- und "
      "Bringservice oder Ersatzfahrzeuge enthalten sind. Ein günstiger "
      "Stundensatz nützt wenig, wenn das Fahrzeug tagelang steht.\n\n"
      "3. Kapazität und Zulassungen: Die Werkstatt muss die zusätzliche Menge "
      "von 80 Fahrzeugen tatsächlich aufnehmen können und über die "
      "erforderlichen Berechtigungen verfügen – etwa die Anerkennung für "
      "Sicherheitsprüfungen und die Vorbereitung der Hauptuntersuchung nach "
      "§ 29 StVZO, Herstellerautorisierung für die Garantieabwicklung sowie ein "
      "zertifiziertes Qualitätsmanagement, das zum eigenen System nach "
      "DIN EN ISO 9001 passt.\n\n"
      "Sinnvoll sind ergänzend eine Probephase mit wenigen Fahrzeugen und die "
      "Vereinbarung messbarer Leistungskennzahlen (Standzeiten, Termintreue, "
      "Nacharbeitsquote).",
 "e": "Die Nutzwertanalyse liefert eine Rangfolge, keine Entscheidung – harte "
      "Faktoren wie Bonität, Vertragsdetails und Kapazität kommen hinzu."
},
"OK|8. Mai 2025|1|c": {
 "a": "Arbeiten an Fahrzeugen mit Hochvoltsystemen (Spannungen über 60 V "
      "Gleichspannung) setzen besondere Voraussetzungen voraus. Drei davon sind "
      "entscheidend:\n\n"
      "1. Qualifiziertes Personal: Die Werkstatt muss über Mitarbeiter mit einer "
      "Hochvolt-Qualifikation nach DGUV Information 200-005 verfügen. Diese "
      "unterscheidet drei Stufen – Stufe 1 (sensibilisierte Person für Arbeiten "
      "an nicht eigensicheren Fahrzeugen), Stufe 2 (fachkundig für Arbeiten am "
      "spannungsfrei geschalteten HV-System) und Stufe 3 (Arbeiten unter "
      "Spannung). Für Instandsetzung am HV-System ist mindestens Stufe 2 "
      "erforderlich, dazu eine schriftlich bestellte verantwortliche "
      "Elektrofachkraft.\n\n"
      "2. Geeignete Ausrüstung und Schutzmittel: Erforderlich sind isolierte "
      "Werkzeuge (1.000 V), persönliche Schutzausrüstung mit Isolierhandschuhen "
      "der Schutzklasse 0 und Gesichtsschutz, zweipoliger Spannungsprüfer für "
      "den Nachweis der Spannungsfreiheit sowie Absperrmaterial und "
      "Warnkennzeichnung für den HV-Arbeitsplatz. Die Schutzmittel unterliegen "
      "wiederkehrenden Prüfungen.\n\n"
      "3. Räumliche und organisatorische Voraussetzungen: Nötig sind ein "
      "abgegrenzter, gekennzeichneter HV-Arbeitsbereich, ein festgelegter und "
      "dokumentierter Freischaltprozess (freischalten, gegen Wiedereinschalten "
      "sichern, Spannungsfreiheit feststellen) sowie ein Konzept für den Umgang "
      "mit beschädigten Traktionsbatterien – Quarantäneplatz mit ausreichendem "
      "Sicherheitsabstand, Brandschutzvorkehrungen und geregelte Entsorgung.\n\n"
      "Zusätzlich sollte die Werkstatt über Diagnosegeräte und Herstellerzugang "
      "für die betreffenden Fahrzeugtypen verfügen.",
 "e": "Merke die drei Säulen: qualifizierte Personen, geprüfte Ausrüstung, "
      "abgegrenzter Arbeitsbereich mit dokumentiertem Freischaltprozess."
},

"OK|8. Mai 2025|2|a": {
 "a": "Durch die Umstellung auf Elektrotransporter treten Gefährdungen auf, die "
      "es bei Dieselfahrzeugen nicht gab. Drei davon sind zwingend in die "
      "Gefährdungsbeurteilung aufzunehmen:\n\n"
      "1. Elektrische Gefährdung durch das Hochvoltsystem: Traktionsbatterie und "
      "Leitungen führen Spannungen weit über der für den Menschen gefährlichen "
      "Grenze von 60 V Gleichspannung. Beim Berühren beschädigter (orange "
      "gekennzeichneter) Leitungen, beim unsachgemäßen Öffnen von Komponenten "
      "oder durch Restspannung in den Zwischenkreiskondensatoren drohen "
      "Stromschlag, Herzkammerflimmern und Lichtbogenverletzungen. Betroffen "
      "sind Werkstattmitarbeiter, aber auch Fahrer nach einem Unfall.\n\n"
      "2. Chemisch-thermische Gefährdung durch die Traktionsbatterie: Bei "
      "Beschädigung, Überladung oder Tiefentladung kann es zum thermischen "
      "Durchgehen kommen. Die Folge sind sehr heiße, schwer löschbare Brände mit "
      "Wiederentzündungsgefahr sowie das Austreten von Elektrolyt und giftigen "
      "Gasen, unter anderem Fluorwasserstoff. Das betrifft Werkstatt, Ladeplatz "
      "und Abstellflächen gleichermaßen.\n\n"
      "3. Mechanische Gefährdung durch Gewicht und Geräuscharmut: Die Batterie "
      "wiegt mehrere hundert Kilogramm; ihr Aus- und Einbau erfordert geeignete "
      "Hebezeuge, sonst drohen Quetschungen und Rückenbelastungen. Zugleich "
      "fahren Elektrofahrzeuge im Rangier- und Schrittbereich nahezu lautlos – "
      "auf dem Betriebshof steigt dadurch die Gefahr, dass Fußgänger sie "
      "überhören und angefahren werden.\n\n"
      "Ergänzend aufzunehmen sind Gefährdungen an der Ladeinfrastruktur "
      "(Stolperstellen durch Ladekabel, Lichtbogen beim Stecken unter Last) "
      "sowie das veränderte Fahrverhalten durch den tiefen Schwerpunkt und das "
      "hohe Drehmoment.",
 "e": "Drei neue Gefährdungsfelder: elektrisch (Hochvolt), chemisch-thermisch "
      "(Batterie), mechanisch (Gewicht und Geräuscharmut)."
},
"OK|8. Mai 2025|2|b": {
 "a": "Drei rechtliche Grundlagen für die Überarbeitung der "
      "Fahrerunterweisungen:\n\n"
      "1. Arbeitsschutzgesetz (ArbSchG), insbesondere §§ 5 und 12: § 5 "
      "verpflichtet den Arbeitgeber, die Gefährdungen zu beurteilen – bei neuer "
      "Technik ist die Beurteilung zu aktualisieren. § 12 verlangt, die "
      "Beschäftigten über Sicherheit und Gesundheitsschutz zu unterweisen, und "
      "zwar vor Aufnahme der Tätigkeit, bei Veränderungen im Aufgabenbereich – "
      "wie hier durch die neuen Antriebe – und danach mindestens jährlich. "
      "Konkretisiert wird das durch § 4 der DGUV Vorschrift 1.\n\n"
      "2. DGUV Vorschrift 3 „Elektrische Anlagen und Betriebsmittel“ in "
      "Verbindung mit der DGUV Information 200-005 „Qualifizierung für Arbeiten "
      "an Fahrzeugen mit Hochvoltsystemen“: Sie legt fest, wer an "
      "Hochvoltsystemen tätig werden darf, und sieht abgestufte "
      "Qualifikationen vor. Für Fahrer ist mindestens die Sensibilisierung "
      "(Stufe 1) erforderlich: Erkennen der orange gekennzeichneten HV-Bauteile, "
      "Verbot des Eingriffs, richtiges Verhalten bei Unfall, Panne und "
      "Warnmeldungen.\n\n"
      "3. Betriebssicherheitsverordnung (BetrSichV), §§ 3 und 12: Fahrzeuge und "
      "Ladeeinrichtungen sind Arbeitsmittel. § 3 verlangt die "
      "Gefährdungsbeurteilung vor ihrer Verwendung einschließlich der Festlegung "
      "erforderlicher Prüfungen; § 12 verpflichtet zur Unterweisung über die "
      "sichere Verwendung, insbesondere über vorhersehbare Betriebsstörungen und "
      "das Verhalten in solchen Fällen – etwa bei einer Störung während des "
      "Ladevorgangs.\n\n"
      "Ergänzend zu beachten sind die Arbeitsstättenverordnung für den "
      "Ladeplatz sowie die Betriebsanleitung des Herstellers, deren Vorgaben "
      "nach § 12 BetrSichV in die Unterweisung einfließen müssen.",
 "e": "ArbSchG regelt das Ob und Wann der Unterweisung, DGUV die "
      "Hochvolt-Qualifikation, BetrSichV das Arbeitsmittel und seine Prüfung."
},
"OK|8. Mai 2025|2|c": {
 "a": "§ 3 der Betriebssicherheitsverordnung verpflichtet den Arbeitgeber, vor "
      "der Verwendung eines Arbeitsmittels eine Gefährdungsbeurteilung "
      "durchzuführen und daraus die notwendigen Schutzmaßnahmen sowie Art, "
      "Umfang und Fristen erforderlicher Prüfungen abzuleiten.\n\n"
      "Konkrete Maßnahme für die E-Ladesäule: Vor der ersten Inbetriebnahme wird "
      "die Ladesäule einschließlich ihrer elektrischen Anschlüsse durch eine "
      "befähigte Person – hier eine Elektrofachkraft – auf ordnungsgemäße "
      "Installation und sichere Funktion geprüft. Aus der "
      "Gefährdungsbeurteilung wird zugleich eine wiederkehrende Prüffrist "
      "festgelegt (in der Praxis üblicherweise jährlich, bei ortsfesten Anlagen "
      "nach DGUV Vorschrift 3 auch längere Intervalle). Jede Prüfung wird mit "
      "Datum, Prüfer und Ergebnis dokumentiert; festgestellte Mängel führen bis "
      "zu ihrer Beseitigung zur Sperrung der Ladesäule.\n\n"
      "Damit ist sichergestellt, dass Isolationsfehler, beschädigte Ladekabel "
      "oder ein defekter Fehlerstromschutzschalter erkannt werden, bevor sie zu "
      "einem Stromunfall oder Brand führen.",
 "e": "§ 3 BetrSichV = Gefährdungsbeurteilung vor Verwendung, daraus folgen "
      "Schutzmaßnahmen UND Prüffristen durch eine befähigte Person."
},

"OK|8. Mai 2025|3|a": {
 "a": "Vier wesentliche Risiken im Fuhrpark und je eine Maßnahme zur "
      "Minimierung:\n\n"
      "1. Unfallrisiko im Fahrbetrieb\n"
      "Zusammenstöße, Rangier- und Parkschäden treiben die Schadenquote und "
      "damit die Versicherungsprämie. Maßnahme: regelmäßige Fahrsicherheits- "
      "und Rangiertrainings, ergänzt um eine Telematikauswertung des "
      "Fahrverhaltens (Bremsen, Beschleunigen, Kurvengeschwindigkeit) mit "
      "individueller Rückmeldung an den Fahrer sowie eine konsequente Auswertung "
      "jedes Schadens auf seine Ursache.\n\n"
      "2. Halterhaftung und Organisationsverschulden\n"
      "Kommt der Halter seinen Überwachungspflichten nicht nach, haften "
      "Geschäftsführung und Fuhrparkleiter persönlich (§ 31 StVZO, § 130 OWiG). "
      "Maßnahme: schriftliche Pflichtenübertragung nach § 13 ArbSchG, "
      "dokumentierte Führerscheinkontrolle in festen Abständen, nachweisbare "
      "Abfahrtkontrollen und lückenlose Fristenüberwachung für "
      "Hauptuntersuchung, Sicherheitsprüfung und UVV-Prüfung.\n\n"
      "3. Risiko mangelhafter Ladungssicherung\n"
      "Trotz Schulungen kam es bei BALM-Kontrollen zu Beanstandungen; drohen "
      "Bußgelder, Weiterfahrverbote und im Schadensfall Regress des "
      "Versicherers. Maßnahme: verbindliche Lastverteilungspläne je "
      "Fahrzeugtyp, Bereitstellung geeigneter und geprüfter Sicherungsmittel, "
      "praktische Unterweisung am Fahrzeug statt nur theoretischer Schulung "
      "sowie stichprobenartige Ausgangskontrollen mit dokumentiertem Ergebnis.\n\n"
      "4. Diebstahl- und Ladungsverlustrisiko\n"
      "Betroffen sind Fahrzeuge, Kraftstoff und hochwertige Stückgüter, bei den "
      "Kühlfahrzeugen zusätzlich temperaturgeführte Ware. Maßnahme: gesichertes "
      "und beleuchtetes Betriebsgelände mit Zutrittskontrolle, GPS-Ortung der "
      "Fahrzeuge, verbindliche Regeln für bewachte Standplätze bei "
      "Übernachtungen sowie Temperaturüberwachung mit Alarmierung bei den "
      "Kühlaufliegern.\n\n"
      "Diese Maßnahmen senken nicht nur das Haftungsrisiko, sondern verbessern "
      "über die Schadenquote unmittelbar die Verhandlungsposition gegenüber dem "
      "Versicherer.",
 "e": "Immer Risiko UND passende Maßnahme paaren – und die Maßnahme so "
      "beschreiben, dass sie nachweisbar ist (Dokumentation!)."
},
"OK|8. Mai 2025|3|b": {
 "a": "Ein Prämiensystem belohnt Fahrer für schadenfreies oder schadenarmes "
      "Fahren, etwa durch eine jährliche Zahlung bei unfallfreier Fahrpraxis.\n\n"
      "Drei Vorteile\n\n"
      "1. Wirksamer Anreiz und höhere Aufmerksamkeit: Der Fahrer hat einen "
      "unmittelbaren eigenen Nutzen von vorsichtiger Fahrweise. Erfahrungsgemäß "
      "gehen vor allem die vielen kleinen, selbstverschuldeten Rangier- und "
      "Parkschäden zurück, die den größten Teil der Schadenmeldungen ausmachen.\n\n"
      "2. Sinkende Kosten: Weniger Schäden bedeuten geringere "
      "Reparaturaufwendungen, kürzere Ausfallzeiten und eine bessere "
      "Schadenquote – letztere wirkt direkt auf die Versicherungsprämie, deren "
      "Anstieg ja der Anlass dieser Prüfung ist.\n\n"
      "3. Wertschätzung und Bindung: Die Prämie würdigt sorgfältiges Arbeiten "
      "sichtbar. In einem Umfeld mit Fachkräftemangel und altersbedingten "
      "Abgängen stärkt das die Zufriedenheit und hilft, erfahrene Fahrer zu "
      "halten.\n\n"
      "Drei Nachteile\n\n"
      "1. Anreiz zum Verschweigen von Schäden: Wer die Prämie nicht verlieren "
      "will, meldet kleine Schäden womöglich nicht. Mängel bleiben unentdeckt, "
      "die Verkehrssicherheit leidet, und die Reparatur wird später teurer. "
      "Dieser Effekt kann das ganze System ins Gegenteil verkehren.\n\n"
      "2. Empfundene Ungerechtigkeit: Ein Fahrer im Fernverkehr hat ein deutlich "
      "geringeres Schadenrisiko als ein Kollege, der täglich in engen "
      "Innenstädten und an Rampen rangiert. Ohne Differenzierung entsteht Neid, "
      "und ein unverschuldeter Schaden wird als doppelte Bestrafung erlebt.\n\n"
      "3. Rechtlicher und organisatorischer Aufwand: Ein Prämiensystem ist eine "
      "Frage der betrieblichen Lohngestaltung und damit nach § 87 Abs. 1 Nr. 10 "
      "und 11 BetrVG mitbestimmungspflichtig – der Betriebsrat muss zustimmen. "
      "Hinzu kommen laufende Erfassung, Bewertung strittiger Fälle und ein "
      "Gewöhnungseffekt: Ist die Prämie einmal eingeführt, wird sie als "
      "Besitzstand betrachtet und lässt sich kaum zurücknehmen.",
 "e": "Der gefährlichste Nachteil ist das Verschweigen kleiner Schäden – "
      "deshalb Prämien nie allein an die reine Schadenfreiheit knüpfen."
},

"OK|8. Mai 2025|4|a": {
 "a": "Variable Kosten je Kilometer\n\n"
      "Kalkulatorische Abschreibung (variabler Anteil):\n"
      "Abschreibung gesamt = 270.000 € ÷ 10 Jahre = 27.000,00 €/Jahr\n"
      "davon 40 % variabel = 27.000 € × 0,40 = 10.800,00 €/Jahr\n"
      "je Kilometer: 10.800 € ÷ 96.000 km = 0,1125 €/km\n\n"
      "Kraftstoffkosten:\n"
      "35 l ÷ 100 km × 1,20 €/l = 0,42 €/km\n\n"
      "Reparaturkosten:\n"
      "3.600 € ÷ 96.000 km = 0,0375 €/km\n\n"
      "Summe der variablen Kosten:\n"
      "0,1125 + 0,42 + 0,0375 = 0,57 €/km\n\n"
      "Die variablen Kosten betragen 0,57 €/km.",
 "e": "Variabel sind hier nur drei Positionen: der Abschreibungsanteil von "
      "40 %, der Kraftstoff und die Reparaturen."
},
"OK|8. Mai 2025|4|b": {
 "a": "Gesamte fixe Kosten je Einsatztag\n\n"
      "Kalkulatorische Abschreibung (fixer Anteil):\n"
      "27.000 € × 0,60 = 16.200,00 €/Jahr\n\n"
      "Kalkulatorische Zinsen:\n"
      "Verzinst wird das durchschnittlich gebundene Kapital, also der halbe "
      "Anschaffungswert: 270.000 € ÷ 2 = 135.000 € × 5 % = 6.750,00 €/Jahr\n\n"
      "Weitere feste Kosten:\n"
      "Fahrerlohn einschließlich Nebenkosten: 57.600,00 €\n"
      "Kalkulatorischer Unternehmerlohn: 4.000,00 €\n"
      "Kalkulatorisches Unternehmerrisiko: 3.000,00 €\n"
      "Kfz-Steuer: 2.800,00 €\n"
      "Kfz-Versicherung: 10.200,00 €\n\n"
      "Summe der fixen Kosten:\n"
      "16.200 + 6.750 + 57.600 + 4.000 + 3.000 + 2.800 + 10.200 "
      "= 100.550,00 €/Jahr\n\n"
      "Je Einsatztag:\n"
      "100.550,00 € ÷ 240 Einsatztage = 418,96 €/Tag\n\n"
      "Hinweis zur Zinsbasis: Wird stattdessen der volle Anschaffungswert "
      "verzinst (270.000 € × 5 % = 13.500 €), ergeben sich 107.300,00 €/Jahr "
      "beziehungsweise 447,08 €/Tag. Die Verzinsung des halben "
      "Anschaffungswerts ist in der Fahrzeugkostenrechnung üblich, weil das "
      "gebundene Kapital durch die Abschreibung stetig freigesetzt wird.",
 "e": "Fixkosten sind alle zeitabhängigen Positionen – einschließlich "
      "Fahrerlohn, Unternehmerlohn und Unternehmerrisiko."
},
"OK|8. Mai 2025|4|c": {
 "a": "Fahrzeugkosten je 100 kg Fracht\n\n"
      "Kosten der Tagestour:\n"
      "Fixe Kosten für einen Einsatztag: 418,96 €\n"
      "Variable Kosten: 0,57 €/km × 320 km = 182,40 €\n"
      "Gesamtkosten der Tour = 418,96 € + 182,40 € = 601,36 €\n\n"
      "Transportierte Fracht:\n"
      "Nutzlast 24 t = 24.000 kg, davon 60 % Auslastung\n"
      "24.000 kg × 0,60 = 14.400 kg, das entspricht 144 Einheiten zu 100 kg\n\n"
      "Kosten je 100 kg:\n"
      "601,36 € ÷ 144 = 4,18 €\n\n"
      "Die Fahrzeugkosten betragen 4,18 € je 100 kg Fracht.\n\n"
      "Zur Einordnung: Bei voller Auslastung (24.000 kg = 240 Einheiten) wären "
      "es nur 2,51 € je 100 kg. Die geringe Auslastung verteuert die "
      "Beförderung also um rund zwei Drittel – ein starkes Argument für "
      "bessere Tourenplanung und Beiladungen.",
 "e": "Erst die gesamten Tourkosten bilden (Fixkosten je Tag + variable Kosten "
      "× Strecke), dann durch die tatsächlich beförderte Menge teilen."
},

"OK|8. Mai 2025|5|a": {
 "a": "Zwei Gründe für eine Potenzialanalyse bei den zu übernehmenden "
      "Auszubildenden:\n\n"
      "1. Die richtige Person auf die richtige Stelle setzen: Aus der "
      "Ausbildung ist nur bekannt, wie die jungen Mitarbeiter die vorgegebenen "
      "Ausbildungsaufgaben bewältigt haben. Für die künftige Verwendung sagt das "
      "wenig aus. Die Potenzialanalyse zeigt, wer sich eher für die Werkstatt, "
      "die Disposition, das Lager oder perspektivisch für eine Führungsaufgabe "
      "eignet. So wird die Übernahme nicht nach Sympathie oder Zufall "
      "entschieden, sondern nachvollziehbar und begründbar – das ist auch "
      "gegenüber dem Betriebsrat und den Betroffenen wichtig.\n\n"
      "2. Entwicklung planen und Fachkräfte binden: Das Unternehmen verliert in "
      "den kommenden Jahren erfahrene Mitarbeiter; die Nachfolge muss "
      "vorbereitet werden. Die Analyse macht sichtbar, welche Fähigkeiten "
      "vorhanden, aber noch nicht ausgeschöpft sind, und liefert damit die "
      "Grundlage für gezielte Weiterbildung statt Gießkannenprinzip. Wer eine "
      "erkennbare Perspektive erhält, bleibt dem Betrieb eher erhalten – ein "
      "gewichtiges Argument in einem Markt mit Fachkräftemangel.",
 "e": "Zwei Stoßrichtungen: passgenaue Verwendung heute und Nachfolgeplanung "
      "für morgen."
},
"OK|8. Mai 2025|5|b": {
 "a": "Die Potenzialanalyse hat zwei kennzeichnende Aufgaben:\n\n"
      "1. Sie ist zukunftsgerichtet: Anders als die Leistungsbeurteilung, die "
      "die erbrachte Leistung der Vergangenheit bewertet, fragt die "
      "Potenzialanalyse danach, was ein Mitarbeiter künftig leisten könnte. Sie "
      "erfasst die noch nicht ausgeschöpften Fähigkeiten, die Lern- und "
      "Entwicklungsfähigkeit sowie die Bereitschaft, weiterführende Aufgaben zu "
      "übernehmen. Ein Auszubildender kann in der Routine unauffällig sein und "
      "trotzdem großes Entwicklungspotenzial besitzen.\n\n"
      "2. Sie gleicht Fähigkeiten mit Anforderungen ab: Die beobachteten "
      "fachlichen, methodischen, sozialen und persönlichen Kompetenzen werden "
      "den Anforderungsprofilen der künftig zu besetzenden Stellen "
      "gegenübergestellt. Aus der Differenz ergibt sich der konkrete "
      "Entwicklungsbedarf – also welche Qualifizierung notwendig ist, damit "
      "jemand eine bestimmte Aufgabe übernehmen kann. Damit ist die Analyse die "
      "Grundlage für Personalentwicklung, Nachfolgeplanung und "
      "Laufbahnentscheidungen.",
 "e": "Leistungsbeurteilung schaut zurück, Potenzialanalyse schaut nach vorn – "
      "und misst gegen ein Anforderungsprofil."
},
"OK|8. Mai 2025|5|c": {
 "a": "Die Potenzialeinschätzung läuft in drei Phasen ab:\n\n"
      "1. Vorbereitung\n"
      "Zunächst wird festgelegt, wofür überhaupt eingeschätzt wird: Für welche "
      "künftigen Stellen besteht Bedarf, und welche Anforderungen stellen sie? "
      "Daraus werden die Beobachtungskriterien und ihre Gewichtung abgeleitet "
      "und in einem Beobachtungsbogen festgehalten. Es wird entschieden, welche "
      "Verfahren zum Einsatz kommen (strukturiertes Interview, Arbeitsprobe, "
      "Übungen, Beurteilung durch Ausbilder). Die Beobachter werden geschult, "
      "die Auszubildenden über Zweck, Ablauf und Verwendung der Ergebnisse "
      "informiert, und der Betriebsrat wird beteiligt.\n\n"
      "2. Durchführung und Beobachtung\n"
      "Die Auszubildenden durchlaufen die festgelegten Verfahren. Mehrere "
      "geschulte Beobachter halten das gezeigte Verhalten getrennt voneinander "
      "auf dem Beobachtungsbogen fest. Entscheidend ist die strikte Trennung von "
      "Beobachten und Bewerten: Zunächst wird nur notiert, was tatsächlich "
      "geschehen ist, ohne Interpretation. Das reduziert typische "
      "Beurteilungsfehler wie den ersten Eindruck, den Halo-Effekt oder die "
      "Tendenz zur Mitte.\n\n"
      "3. Auswertung und Rückmeldung\n"
      "In einer Beobachterkonferenz werden die Einzelurteile zusammengeführt, "
      "Abweichungen diskutiert und zu einem Gesamtbild verdichtet. Anschließend "
      "erhält jeder Auszubildende ein persönliches Feedbackgespräch, in dem "
      "Stärken und Entwicklungsfelder konkret an Beispielen erläutert werden. "
      "Daraus werden verbindliche Entwicklungsmaßnahmen und Ziele vereinbart "
      "und dokumentiert; sie fließen in die Personalentwicklungsplanung ein.",
 "e": "Vorbereiten (Kriterien und Beobachter) – Beobachten (trennen von "
      "Bewerten) – Auswerten und zurückmelden (mit Zielvereinbarung)."
},

}
